//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.17929")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.0")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_2re5yaag {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_2re5yaag() {
        }
        
        static object Create_ASP__Page_Admin_Leather_ModifyLeather_cshtml() {
            return new ASP._Page_Admin_Leather_ModifyLeather_cshtml();
        }
        
        static object Create_ASP__Page_Admin_Leather_AddLeather_cshtml() {
            return new ASP._Page_Admin_Leather_AddLeather_cshtml();
        }
        
        static object Create_ASP__Page_Admin_Leather_ReoveLeather_cshtml() {
            return new ASP._Page_Admin_Leather_ReoveLeather_cshtml();
        }
    }
}
