#pragma checksum "G:\Company\MensClothe\ShoppingCart.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5122E538B2391C1798E6281F1F8D86A07895D6A3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_ShoppingCart_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_ShoppingCart_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 86), Tuple.Create("\"", 124)
, Tuple.Create(Tuple.Create("", 92), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 92), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 148), Tuple.Create("\"", 198)
, Tuple.Create(Tuple.Create("", 154), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 154), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 8 "G:\Company\MensClothe\ShoppingCart.cshtml"
  
   
       
    
    ProfileCommon profile = HttpContext.Current.Profile as ProfileCommon;
    var items = profile.SCart.Items;
   
    
    
    
    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("    ");

            
            #line 23 "G:\Company\MensClothe\ShoppingCart.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n\r\n    <fieldset>\r\n        <legend>Clothe Results </legend>\r\n        <div");

WriteLiteral(" id=\"detailform\"");

WriteLiteral("  >\r\n            <table>\r\n                <tr>\r\n                    <td>\r\n       " +
"                 <label>\r\n                            <b>Price</b></label>\r\n    " +
"                </td>\r\n\r\n                    <td>\r\n                        <labe" +
"l");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(">\r\n                            <b>Quantity</b>\r\n                        </label>\r" +
"\n\r\n                    </td>\r\n\r\n                    <td>\r\n                      " +
"  <label");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(@">
                            <b>Image</b>
                        </label>
                    </td>


                    <td>
                        <label>
                            <b>Description</b></label>
                    </td>

                    <td>
                        <label>
                            <b>SubTotal</b></label>
                    </td>

                </tr>

");

            
            #line 62 "G:\Company\MensClothe\ShoppingCart.cshtml"
                
            
            #line default
            #line hidden
            
            #line 62 "G:\Company\MensClothe\ShoppingCart.cshtml"
                 foreach (var item in items)
                { 

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>\r\n                         " +
"   <label");

WriteLiteral(" id=\"Price\"");

WriteLiteral(">");

            
            #line 66 "G:\Company\MensClothe\ShoppingCart.cshtml"
                                         Write(item.Price);

            
            #line default
            #line hidden
WriteLiteral(" </label>\r\n                        </td>\r\n                        <td>\r\n\r\n       " +
"                     <label");

WriteLiteral(" id=\"quantity\"");

WriteLiteral(">");

            
            #line 70 "G:\Company\MensClothe\ShoppingCart.cshtml"
                                            Write(item.Quantity);

            
            #line default
            #line hidden
WriteLiteral(" </label>\r\n                        </td>\r\n                        <td>\r\n         " +
"                   <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1878), Tuple.Create("\"", 1960)
            
            #line 73 "G:\Company\MensClothe\ShoppingCart.cshtml"
, Tuple.Create(Tuple.Create("", 1884), Tuple.Create<System.Object, System.Int32>(MensClothe.AspControlUtil.getFullImagePath(Convert.ToString(item.ImageUrl))
            
            #line default
            #line hidden
, 1884), false)
);

WriteLiteral(" alt=\"Red dot\"");

WriteLiteral(" width=\"100\"");

WriteLiteral(" height=\"150\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                  " +
"          <label");

WriteLiteral(" id=\"Description\"");

WriteLiteral(">");

            
            #line 77 "G:\Company\MensClothe\ShoppingCart.cshtml"
                                               Write(item.ProductName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        </td>\r\n\r\n                        <td>\r\n        " +
"                    <label");

WriteLiteral(" id=\"SubTotal\"");

WriteLiteral(">");

            
            #line 81 "G:\Company\MensClothe\ShoppingCart.cshtml"
                                            Write(item.SubTotal);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        </td>\r\n\r\n\r\n\r\n                    </tr>\r\n");

            
            #line 87 "G:\Company\MensClothe\ShoppingCart.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </table>\r\n             \r\n                <input");

WriteLiteral(" id=\"Check Out\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" name=\"Check Out\"");

WriteLiteral(" value=\"Check Out\"");

WriteLiteral("  />\r\n             \r\n        </div>\r\n    </fieldset>\r\n    <ul>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2703), Tuple.Create("\"", 2712)
, Tuple.Create(Tuple.Create("", 2710), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 2710), false)
);

WriteLiteral(">Home</a></li>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2743), Tuple.Create("\"", 2763)
, Tuple.Create(Tuple.Create("", 2750), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Admin")
, 2750), false)
);

WriteLiteral(">Admin</a></li>\r\n    </ul>\r\n</form>\r\n\r\n");

        }
    }
}
