#pragma checksum "G:\Company\MensClothe\_SiteLayout.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "CB9C1C3157679D7B40602F7AFADD030B1BEB3E46"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page__SiteLayout_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page__SiteLayout_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n    <head>\r\n        <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n        <title>");

            
            #line 5 "G:\Company\MensClothe\_SiteLayout.cshtml"
          Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET Web Page</title>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 152), Tuple.Create("\"", 198)
, Tuple.Create(Tuple.Create("", 159), Tuple.Create<System.Object, System.Int32>(Href("~/Content/themes/base/jquery.ui.all.css")
, 159), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 250), Tuple.Create("\"", 275)
, Tuple.Create(Tuple.Create("", 257), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Site.css")
, 257), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 327), Tuple.Create("\"", 347)
, Tuple.Create(Tuple.Create("", 334), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 334), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 408), Tuple.Create("\"", 443)
, Tuple.Create(Tuple.Create("", 414), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-1.7.1.min.js")
, 414), false)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 471), Tuple.Create("\"", 506)
, Tuple.Create(Tuple.Create("", 477), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-ui-1.8.20.js")
, 477), false)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 534), Tuple.Create("\"", 568)
, Tuple.Create(Tuple.Create("", 540), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/modernizr-2.5.3.js")
, 540), false)
);

WriteLiteral("></script>\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    </head>\r\n    <body>\r\n        <header>\r\n            <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"float-left\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"site-title\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 816), Tuple.Create("\"", 825)
, Tuple.Create(Tuple.Create("", 823), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 823), false)
);

WriteLiteral(">your logo here</a></p>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"float-right\"");

WriteLiteral(">\r\n                    <section");

WriteLiteral(" id=\"login\"");

WriteLiteral(">\r\n");

            
            #line 22 "G:\Company\MensClothe\_SiteLayout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 22 "G:\Company\MensClothe\_SiteLayout.cshtml"
                         if (WebSecurity.IsAuthenticated) {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("\r\n                                Hello, <a");

WriteLiteral(" class=\"email\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1112), Tuple.Create("\"", 1135)
, Tuple.Create(Tuple.Create("", 1119), Tuple.Create<System.Object, System.Int32>(Href("~/Account/Manage")
, 1119), false)
);

WriteLiteral(" title=\"Manage\"");

WriteLiteral(">");

            
            #line 24 "G:\Company\MensClothe\_SiteLayout.cshtml"
                                                                                          Write(WebSecurity.CurrentUserName);

            
            #line default
            #line hidden
WriteLiteral("</a>!\r\n                                <form");

WriteLiteral(" id=\"logoutForm\"");

WriteAttribute("action", Tuple.Create(" action=\"", 1240), Tuple.Create("\"", 1265)
, Tuple.Create(Tuple.Create("", 1249), Tuple.Create<System.Object, System.Int32>(Href("~/Account/Logout")
, 1249), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 26 "G:\Company\MensClothe\_SiteLayout.cshtml"
                               Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <a");

WriteLiteral(" href=\"javascript:document.getElementById(\'logoutForm\').submit()\"");

WriteLiteral(">Log out</a>\r\n                                </form>\r\n                          " +
"  ");

WriteLiteral("\r\n");

            
            #line 30 "G:\Company\MensClothe\_SiteLayout.cshtml"
                        } else {

            
            #line default
            #line hidden
WriteLiteral("                            <ul>\r\n                                <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1644), Tuple.Create("\"", 1669)
, Tuple.Create(Tuple.Create("", 1651), Tuple.Create<System.Object, System.Int32>(Href("~/Account/Register")
, 1651), false)
);

WriteLiteral(">Register</a></li>\r\n                                <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1728), Tuple.Create("\"", 1750)
, Tuple.Create(Tuple.Create("", 1735), Tuple.Create<System.Object, System.Int32>(Href("~/Account/Login")
, 1735), false)
);

WriteLiteral(">Log in</a></li>\r\n                            </ul>\r\n");

            
            #line 35 "G:\Company\MensClothe\_SiteLayout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </section>\r\n                    <nav>\r\n                      " +
"  <ul");

WriteLiteral(" id=\"menu\"");

WriteLiteral(">\r\n                            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1964), Tuple.Create("\"", 1973)
, Tuple.Create(Tuple.Create("", 1971), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 1971), false)
);

WriteLiteral(">Home</a></li>\r\n                            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2024), Tuple.Create("\"", 2038)
, Tuple.Create(Tuple.Create("", 2031), Tuple.Create<System.Object, System.Int32>(Href("~/About")
, 2031), false)
);

WriteLiteral(">About</a></li>\r\n                            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2090), Tuple.Create("\"", 2106)
, Tuple.Create(Tuple.Create("", 2097), Tuple.Create<System.Object, System.Int32>(Href("~/Contact")
, 2097), false)
);

WriteLiteral(">Contact</a></li>\r\n                            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2160), Tuple.Create("\"", 2180)
, Tuple.Create(Tuple.Create("", 2167), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Admin")
, 2167), false)
);

WriteLiteral(">Admin</a></li>\r\n                        </ul>\r\n                    </nav>\r\n     " +
"           </div>\r\n            </div>\r\n        </header>\r\n        <div");

WriteLiteral(" id=\"body\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 49 "G:\Company\MensClothe\_SiteLayout.cshtml"
       Write(RenderSection("featured", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <section");

WriteLiteral(" class=\"content-wrapper main-content clear-fix\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 51 "G:\Company\MensClothe\_SiteLayout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </section>\r\n        </div>\r\n        <footer>\r\n            <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"float-left\"");

WriteLiteral(">\r\n                    <p>&copy; ");

            
            #line 57 "G:\Company\MensClothe\_SiteLayout.cshtml"
                         Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - Mens Store</p>\r\n                </div>\r\n            </div>\r\n        </footer>\r" +
"\n");

WriteLiteral("        ");

            
            #line 61 "G:\Company\MensClothe\_SiteLayout.cshtml"
   Write(RenderSection("Scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n</html>");

        }
    }
}
