#pragma checksum "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "E0FCEC7A20DDD4F1C55E7074B8D64388B6DB1DA7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Clothes_ModifyClothe_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Clothes_ModifyClothe_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Clothes";
    dynamic ClotheRecord =null ;
    var Price = "";
    var quantity = "";
    var Description = "";
    var size = "";
    var clotheId = 0;
    Database db;
    var items = new List<SelectListItem>();
    var i = 0;
    var ms = new MemoryStream();
  //  byte[] imgArray= null;
    string imgArray = string.Empty;
    Database Dbase = new DbConnection("ConnectionStr").db;
    
    Validation.RequireField("ItemName", "You must specify the  clothe name.");
    Validation.RequireField("Price", "Price cannot be blank.");
    Validation.RequireField("ItemImage", "Choose Item Image");
    Validation.RequireField("Size", "Sizerequired ");

     if (IsPost)
     {
         var detailForm = Request.Form["detailform"];
         var updateDetail = Request.Form["UpdateDetail"];
         var updateConfirm = Request.Form["UpdateConfirm"];

  
         if (!string.IsNullOrEmpty(Request.Form["DDLid"]))
         {
           Session.Add("clotheId", Request.Form["DDLid"]) ;
         }

         if (updateDetail != null && Session["clotheId"] != null)
    {
            clotheId = int.Parse(Session["clotheId"].ToString());
         //   db = Database.Open("mensClothe");
            ClotheRecord = Dbase.QuerySingle("SELECT Description, Price,ItemImage ,QOH, Size FROM  Clothe Where ItemID=@0 ", clotheId);
            if(ClotheRecord != null)
            {
                Price = Convert.ToString( ClotheRecord["Price"]);
                Description = Convert.ToString(ClotheRecord["Description"]);
                quantity =Convert.ToString( ClotheRecord["QOH"]) ;
                size = Convert.ToString(ClotheRecord["Size"]);
                imgArray = ClotheRecord["ItemImage"];
            } 
    }
    else if (updateConfirm != null && Session["clotheId"] != null)
    {

       //ItemName = Request.Form["ItemName"];
       Price = Request.Form["Price"];
       // ItemImage = Request.Form["ItemImage"];
       quantity = Request.Form["quantity"];
       size =Request.Form["size"];
       Description = Request.Form["Description"];
       HttpPostedFileBase file = Request.Files["ItemImage"];
       if (file != null)
       {
           ms = new MemoryStream();
           file.InputStream.CopyTo(ms);
           // imgStream = ms.ToArray();
       }

     //  System.Drawing.Bitmap image = new System.Drawing.Bitmap(ms);
    //   MemoryStream stream = new MemoryStream();
    //   image.Save(stream, System.Drawing.Imaging.ImageFormat.Bmp);
       var img = file.FileName;  //stream.ToArray();
        
       clotheId = int.Parse(Session["clotheId"].ToString());
      // db = Database.Open("mensClothe");
       i = Dbase.Execute("UPDATE  Clothe SET  Price=@0 ,Size=@1,  Description=@2 ,  QOH=@3, ItemImage=@4  WHERE ItemID = @5", Price, size, Description, quantity, img, clotheId);
   
    
    }
    
    
     }
    
    

        

            
        
            
            // Insert a new item into the database
          //   db = Database.Open("mensClothe");

            // Check if user already exists
          
           var user = Dbase.Query("SELECT * FROM  Clothe ");
            
            if(user != null)
            {

               items.Add(new SelectListItem { Text = "Select....", Value = "" });
               foreach(var item in user)
               {

                   items.Add(new SelectListItem { Text = item["ItemName"], Value = Convert.ToString( item["ItemID"]) });
                   
               }
            
            }
            
               
            
        
    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 121 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
   Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Delete Clothe Item</h2>\r\n</hgroup>\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral("  enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 126 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 128 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
Write(Html.ValidationSummary("Adding Clothe was unsuccessful. Please correct the errors and try again.", excludeFieldErrors: true, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <fieldset>\r\n        <legend>Registration Form</legend>\r\n        <ol>\r\n\r\n " +
"           <li");

WriteLiteral(" class=\"Clothes\"");

WriteLiteral(">\r\n                <label  >\r\n                    Select Clothe Item to be Delete" +
"d:\r\n                </label>\r\n");

WriteLiteral("                ");

            
            #line 138 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
           Write(Html.DropDownList("DDLid",    items));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n\r\n            </li>\r\n             \r\n        </ol>\r\n   \r\n    <div");

WriteLiteral(" id=\"detailform\"");

WriteLiteral("   ");

            
            #line 147 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                            if(ClotheRecord == null)
                           {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 148 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                                                              }
            
            #line default
            #line hidden
WriteLiteral("\">\r\n\r\n        <ol>            \r\n\r\n            <li class=\"Price\">\r\n               " +
" <label>\r\n                    Price</label>\r\n                <input type=\"text\" " +
"id=\"Price\" name=\"Price\" value=\"");

            
            #line 155 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                                                             Write(Price);

            
            #line default
            #line hidden
WriteLiteral("\" ) />\r\n                ");

WriteLiteral("\r\n              \r\n            </li>\r\n            <li class=\"ItemImage\">\r\n        " +
"        <label for=\"ItemImage\">\r\n                    Quantity</label>\r\n         " +
"       <input type=\"text\" id=\"quantity\" name=\"quantity\"  value=\"");

            
            #line 162 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                                                                    Write(quantity);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            </li>\r\n\r\n\r\n            <li class=\"ItemImage\">\r\n");

            
            #line 167 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                
            
            #line default
            #line hidden
            
            #line 167 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                 if (imgArray!= null)
                {

            
            #line default
            #line hidden
WriteLiteral("                <label");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(">\r\n                    Image </label>\r\n");

WriteLiteral("                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 5525), Tuple.Create("\"", 5603)
            
            #line 171 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
, Tuple.Create(Tuple.Create("", 5531), Tuple.Create<System.Object, System.Int32>(MensClothe.AspControlUtil.getFullImagePath( Convert.ToString(imgArray))
            
            #line default
            #line hidden
, 5531), false)
);

WriteLiteral(" alt=\"Red dot\"");

WriteLiteral(" width=\"100\"");

WriteLiteral(" height=\"150\"");

WriteLiteral(">  \r\n");

            
            #line 172 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("             </li>\r\n             <li class=\"ItemImage\">\r\n\r\n                 <labe" +
"l for=\"ItemImage\">\r\n                 change   Image </label>\r\n                <l" +
"abel for=\"ItemImage\" ");

            
            #line 178 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                                        if(!ModelState.IsValidField("ItemImage")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 178 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                                                                                                                   }
            
            #line default
            #line hidden
WriteLiteral(">Image of the Clothe</label>\r\n                <input type=\"file\" id=\"ItemImage\" n" +
"ame=\"ItemImage\"  />\r\n                ");

WriteLiteral("\r\n              </li>\r\n\r\n           <li class=\"Size\">\r\n                <label>\r\n " +
"                   Size</label>\r\n                <input type=\"text\" id=\"size\" na" +
"me=\"size\"  value=\"");

            
            #line 186 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                                                            Write(size);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            </li>\r\n\r\n           \r\n            <li class=\"description\">\r\n   " +
"             <label>\r\n                    Description</label>\r\n                <" +
"input type=\"text\" id=\"Desc\" name=\"Description\"  value=\"");

            
            #line 193 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                                                                   Write(Description);

            
            #line default
            #line hidden
WriteLiteral(@""" />
            </li>
            <li class=""recaptcha""></li>
        </ol>
        <input type=""submit"" id=""UpdateConfirm"" name=""UpdateConfirm"" value=""Confirm"" />
       </div>
  </fieldset>
    <p>
    <input type=""submit"" id=""UpdateDetail""  name=""UpdateDetail"" value=""Update Clothe Item""  ");

            
            #line 201 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                                                                                             if (ClotheRecord != null)
                            {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 202 "G:\Company\MensClothe\Admin\Clothes\ModifyClothe.cshtml"
                                                               }
            
            #line default
            #line hidden
WriteLiteral("\" />\r\n   </p>\r\n    <ul>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6942), Tuple.Create("\"", 6951)
, Tuple.Create(Tuple.Create("", 6949), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 6949), false)
);

WriteLiteral(">Home</a></li>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6982), Tuple.Create("\"", 7002)
, Tuple.Create(Tuple.Create("", 6989), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Admin")
, 6989), false)
);

WriteLiteral(">Admin</a></li>\r\n        \r\n    </ul>\r\n</form>");

        }
    }
}
