#pragma checksum "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0B1FE1573135D0B1B8FA4E198B008A3A5C1FF171"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Leather_AddLeather_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Leather_AddLeather_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Leathers";

    // Initialize general page variables
    var ItemName = "";
    var Price = "";
    var ItemImage = "";
    
    var quantity = "";
    var size = "";
    var Description = "";

    // Setup validation
    Validation.RequireField("ItemName", "You must specify the  Leather name.");
    Validation.RequireField("Price", "Price cannot be blank.");
    Validation.RequireField("ItemImage", "Choose Item Image");
    Validation.RequireField("Size", "Sizerequired ");
    
    
    //Validation.Add("confirmPassword",
    //    Validator.EqualsTo("password", "Password and confirmation password do not match."));
    //Validation.Add("password",
    //    Validator.StringLength(
    //        maxLength: Int32.MaxValue,
    //        minLength: 6,
    //        errorMessage: "Password must be at least 6 characters"));

    // If this is a POST request, validate and process data
    if (IsPost) {
        AntiForgery.Validate();

       



        ItemName = Request.Form["ItemName"];
        Price = Request.Form["Price"];
        ItemImage = Request.Form["ItemImage"];

        quantity = Request.Form["quantity"];
        size = Request.Form["size"];
        Description = Request.Form["Description"];

        System.Drawing.Bitmap image = new System.Drawing.Bitmap(ItemImage);
        MemoryStream stream = new MemoryStream();
        image.Save(stream, System.Drawing.Imaging.ImageFormat.Bmp);
        var img= stream.ToArray();
        

        

        // Validate the user's captcha answer
        // if (!ReCaptcha.Validate("PRIVATE_KEY")) {
        //     ModelState.AddError("recaptcha", "Captcha response was not correct");
        // }

        // If all information is valid, create a new account
        if (Validation.IsValid()) {
            
        
            
            // Insert a new user into the database
            var db = Database.Open("mensClothe");

            // Check if user already exists
        //    var user = db.QuerySingle("SELECT Email FROM UserProfile WHERE LOWER(Email) = LOWER(@0)", email);
            
                // Insert email into the profile table
            db.Execute("INSERT INTO Leather (ItemName,Price, ItemImage, QOH, Size,Description) VALUES (@0,@1,@2,@3,@4,@5 )", ItemName, Price, img, quantity, size, Description);

                // Create and associate a new entry in the membership database.
                // If successful, continue processing the request
               
            
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 87 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
   Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Add a new Leather Item</h2>\r\n</hgroup>\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 92 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 94 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
Write(Html.ValidationSummary("Adding Leather was unsuccessful. Please correct the errors and try again.", excludeFieldErrors: true, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <fieldset>\r\n        <legend>Registration Form</legend>\r\n        <ol>\r\n   " +
"         \r\n            <li");

WriteLiteral(" class=\"Leathers\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"Leathers\"");

WriteLiteral(" ");

            
            #line 101 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                       if (!ModelState.IsValidField("ItemName"))
                                     {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 102 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                                                      }
            
            #line default
            #line hidden
WriteLiteral(">Leather Name </label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ItemName\"");

WriteLiteral(" name=\"ItemName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3588), Tuple.Create("\"", 3605)
            
            #line 103 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
, Tuple.Create(Tuple.Create("", 3596), Tuple.Create<System.Object, System.Int32>(ItemName
            
            #line default
            #line hidden
, 3596), false)
);

WriteLiteral(" ");

            
            #line 103 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                                                              Write(Validation.For("ItemName"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 105 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
           Write(Html.ValidationMessage("ItemName"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"Price\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"Price\"");

WriteLiteral(" ");

            
            #line 108 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                    if(!ModelState.IsValidField("Price")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 108 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                                                                                           }
            
            #line default
            #line hidden
WriteLiteral(">Unit Price</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Price\"");

WriteLiteral(" name=\"Price\"");

WriteLiteral(" ");

            
            #line 109 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                                      Write(Validation.For("Price"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 111 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
           Write(Html.ValidationMessage("Price"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"ItemImage\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(" ");

            
            #line 114 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                        if(!ModelState.IsValidField("ItemImage")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 114 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                                                                                                   }
            
            #line default
            #line hidden
WriteLiteral(">Image of the Leather</label>\r\n                <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"ItemImage\"");

WriteLiteral(" name=\"ItemImage\"");

WriteLiteral(" ");

            
            #line 115 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                                              Write(Validation.For("ItemImage"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 117 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
           Write(Html.ValidationMessage("ItemImage"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n               <li");

WriteLiteral(" class=\"ItemImage\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(" ");

            
            #line 120 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                        if(!ModelState.IsValidField("Quantity")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 120 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                                                                                                  }
            
            #line default
            #line hidden
WriteLiteral(">Enter the quantity</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"quantity\"");

WriteLiteral(" name=\"quantity\"");

WriteLiteral(" ");

            
            #line 121 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                                            Write(Validation.For("quantity"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 123 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
           Write(Html.ValidationMessage("Quantity"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"size\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"Size\"");

WriteLiteral(" ");

            
            #line 126 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                   if(!ModelState.IsValidField("Size")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 126 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                                                                                         }
            
            #line default
            #line hidden
WriteLiteral(">Enter the Size </label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Size\"");

WriteLiteral(" name=\"Size\"");

WriteLiteral(" ");

            
            #line 127 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                                    Write(Validation.For("Size"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 129 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
           Write(Html.ValidationMessage("Quantity"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n\r\n            <li");

WriteLiteral(" class=\"description\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(" ");

            
            #line 133 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                        if(!ModelState.IsValidField("Description")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 133 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                                                                                                     }
            
            #line default
            #line hidden
WriteLiteral(">Enter the Description</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Desc\"");

WriteLiteral(" name=\"Description\"");

WriteLiteral(" ");

            
            #line 134 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
                                                           Write(Validation.For("Description"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 136 "G:\Company\MensClothe\Admin\Leather\AddLeather.cshtml"
           Write(Html.ValidationMessage("Description"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"recaptcha\"");

WriteLiteral(">\r\n                \r\n            </li>\r\n        </ol>\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Add Leather\"");

WriteLiteral(" />\r\n    </fieldset>\r\n</form>");

        }
    }
}
