#pragma checksum "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "FBE94E2CBCB6FB561183F1BDA2B38E06EB9163A5"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Cosmetics_AddCosmetic_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Cosmetics_AddCosmetic_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Cosmeticss";

    // Initialize general page variables
    var ItemName = "";
    var Price = "";
    var ItemImage = "";
    
    var quantity = "";
    var size = "";
    var Description = "";

    // Setup validation
    Validation.RequireField("ItemName", "You must specify the  Cosmetics name.");
    Validation.RequireField("Price", "Price cannot be blank.");
    Validation.RequireField("ItemImage", "Choose Item Image");
    Validation.RequireField("Size", "Sizerequired ");
    
    
   
    if (IsPost) {
        AntiForgery.Validate();
        

        ItemName = Request.Form["ItemName"];
        Price = Request.Form["Price"];
        ItemImage = Request.Form["ItemImage"];

        quantity = Request.Form["quantity"];
        size = Request.Form["size"];
        Description = Request.Form["Description"];

        System.Drawing.Bitmap image = new System.Drawing.Bitmap(ItemImage);
        MemoryStream stream = new MemoryStream();
        image.Save(stream, System.Drawing.Imaging.ImageFormat.Bmp);
        var img= stream.ToArray();
        

        

        if (Validation.IsValid()) {
            
        
            
            // Insert a new user into the database
            var db = Database.Open("mensClothe");
            db.Execute("INSERT INTO Cosmetics (ItemName,Price, ItemImage, QOH, Size,Description) VALUES (@0,@1,@2,@3,@4,@5 )", ItemName, Price, img, quantity, size, Description);

                // Create and associate a new entry in the membership database.
                // If successful, continue processing the request
               
            
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 65 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
   Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Add a new Cosmetics Item</h2>\r\n</hgroup>\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 70 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 72 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
Write(Html.ValidationSummary("Adding Cosmetics was unsuccessful. Please correct the errors and try again.", excludeFieldErrors: true, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <fieldset>\r\n        <legend>Registration Form</legend>\r\n        <ol>\r\n   " +
"         \r\n            <li");

WriteLiteral(" class=\"Cosmeticss\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"Cosmeticss\"");

WriteLiteral(" ");

            
            #line 79 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                         if (!ModelState.IsValidField("ItemName"))
                                     {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 80 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                                                      }
            
            #line default
            #line hidden
WriteLiteral(">Cosmetics Name </label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ItemName\"");

WriteLiteral(" name=\"ItemName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2696), Tuple.Create("\"", 2713)
            
            #line 81 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
, Tuple.Create(Tuple.Create("", 2704), Tuple.Create<System.Object, System.Int32>(ItemName
            
            #line default
            #line hidden
, 2704), false)
);

WriteLiteral(" ");

            
            #line 81 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                                                              Write(Validation.For("ItemName"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 83 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
           Write(Html.ValidationMessage("ItemName"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"Price\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"Price\"");

WriteLiteral(" ");

            
            #line 86 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                    if(!ModelState.IsValidField("Price")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 86 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                                                                                           }
            
            #line default
            #line hidden
WriteLiteral(">Unit Price</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Price\"");

WriteLiteral(" name=\"Price\"");

WriteLiteral(" ");

            
            #line 87 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                                      Write(Validation.For("Price"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 89 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
           Write(Html.ValidationMessage("Price"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"ItemImage\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(" ");

            
            #line 92 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                        if(!ModelState.IsValidField("ItemImage")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 92 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                                                                                                   }
            
            #line default
            #line hidden
WriteLiteral(">Image of the Cosmetics</label>\r\n                <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"ItemImage\"");

WriteLiteral(" name=\"ItemImage\"");

WriteLiteral(" ");

            
            #line 93 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                                              Write(Validation.For("ItemImage"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 95 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
           Write(Html.ValidationMessage("ItemImage"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n               <li");

WriteLiteral(" class=\"ItemImage\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(" ");

            
            #line 98 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                        if(!ModelState.IsValidField("Quantity")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 98 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                                                                                                  }
            
            #line default
            #line hidden
WriteLiteral(">Enter the quantity</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"quantity\"");

WriteLiteral(" name=\"quantity\"");

WriteLiteral(" ");

            
            #line 99 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                                            Write(Validation.For("quantity"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 101 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
           Write(Html.ValidationMessage("Quantity"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"size\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"Size\"");

WriteLiteral(" ");

            
            #line 104 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                   if(!ModelState.IsValidField("Size")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 104 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                                                                                         }
            
            #line default
            #line hidden
WriteLiteral(">Enter the Size </label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Size\"");

WriteLiteral(" name=\"Size\"");

WriteLiteral(" ");

            
            #line 105 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                                    Write(Validation.For("Size"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 107 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
           Write(Html.ValidationMessage("Quantity"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n\r\n            <li");

WriteLiteral(" class=\"description\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(" ");

            
            #line 111 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                        if(!ModelState.IsValidField("Description")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 111 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                                                                                                     }
            
            #line default
            #line hidden
WriteLiteral(">Enter the Description</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Desc\"");

WriteLiteral(" name=\"Description\"");

WriteLiteral(" ");

            
            #line 112 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
                                                           Write(Validation.For("Description"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 114 "G:\Company\MensClothe\Admin\Cosmetics\AddCosmetic.cshtml"
           Write(Html.ValidationMessage("Description"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li");

WriteLiteral(" class=\"recaptcha\"");

WriteLiteral(">\r\n                \r\n            </li>\r\n        </ol>\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Add Cosmetics\"");

WriteLiteral(" />\r\n    </fieldset>\r\n</form>");

        }
    }
}
