#pragma checksum "G:\Company\MensClothe\Account\PasswordReset.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3C2983B44A053EE6EC74A2D8D2A1E24350F560DB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Account_PasswordReset_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Account_PasswordReset_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Password Reset";

    var passwordResetToken = Request.Form["resetToken"] ?? Request.QueryString["resetToken"];

    bool tokenExpired = false;
    bool isSuccess = false;

    // Setup validation
    Validation.RequireField("newPassword", "The new password field is required.");
    Validation.Add("confirmPassword",
        Validator.EqualsTo("newPassword", "The new password and confirmation password do not match."));
    Validation.RequireField("passwordResetToken", "The password reset token field is required.");
    Validation.Add("newPassword",
        Validator.StringLength(
            maxLength: Int32.MaxValue,
            minLength: 6,
            errorMessage: "New password must be at least 6 characters"));

    if (IsPost && Validation.IsValid()) {
        AntiForgery.Validate();
        var newPassword = Request["newPassword"];
        var confirmPassword = Request["confirmPassword"];

        if (WebSecurity.ResetPassword(passwordResetToken, newPassword)) {
            isSuccess = true;
        } else {
            ModelState.AddError("passwordResetToken", "The password reset token is invalid.");
            tokenExpired = true;
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 42 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
   Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Use the form below to reset your password.</h2>\r\n</hgroup>\r\n\r\n");

            
            #line 46 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
 if (!WebMail.SmtpServer.IsEmpty()) {
    if (!Validation.IsValid()) {

            
            #line default
            #line hidden
WriteLiteral("        <p");

WriteLiteral(" class=\"validation-summary-errors\"");

WriteLiteral(">\r\n");

            
            #line 49 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
            
            
            #line default
            #line hidden
            
            #line 49 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
             if (tokenExpired) {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("The password reset token is incorrect or may be expired. Visit the <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1849), Tuple.Create("\"", 1880)
, Tuple.Create(Tuple.Create("", 1856), Tuple.Create<System.Object, System.Int32>(Href("~/Account/ForgotPassword")
, 1856), false)
);

WriteLiteral(">forgot password page</a> \r\n                to generate a new one.");

WriteLiteral("\r\n");

            
            #line 52 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("Could not reset password. Please correct the errors and try again.");

WriteLiteral("\r\n");

            
            #line 54 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </p>\r\n");

            
            #line 56 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
    }

    if (isSuccess) {

            
            #line default
            #line hidden
WriteLiteral("        <p");

WriteLiteral(" class=\"message-success\"");

WriteLiteral(">\r\n            Password changed! Click <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2210), Tuple.Create("\"", 2232)
, Tuple.Create(Tuple.Create("", 2217), Tuple.Create<System.Object, System.Int32>(Href("~/Account/Login")
, 2217), false)
);

WriteLiteral(" title=\"Log in\"");

WriteLiteral(">here</a> to log in.\r\n        </p>\r\n");

            
            #line 62 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
    }


            
            #line default
            #line hidden
WriteLiteral("    <form");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 65 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
   Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <fieldset>\r\n            <legend>Password Change Form</legend>\r\n        " +
"    <ol>\r\n                <li");

WriteLiteral(" class=\"new-password\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"newPassword\"");

WriteLiteral(" ");

            
            #line 70 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
                                              if (!ModelState.IsValidField("newPassword")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 70 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
                                                                                                                            }
            
            #line default
            #line hidden
WriteLiteral(">New password</label> \r\n                    <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"newPassword\"");

WriteLiteral(" name=\"newPassword\"");

WriteAttribute("disabled", Tuple.Create(" disabled=\"", 2710), Tuple.Create("\"", 2731)
            
            #line 71 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
         , Tuple.Create(Tuple.Create("", 2721), Tuple.Create<System.Object, System.Int32>(isSuccess
            
            #line default
            #line hidden
, 2721), false)
);

WriteLiteral(" ");

            
            #line 71 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
                                                                                                Write(Validation.For("newPassword"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n");

WriteLiteral("                    ");

            
            #line 72 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
               Write(Html.ValidationMessage("newPassword"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li");

WriteLiteral(" class=\"confirm-password\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"confirmPassword\"");

WriteLiteral(" ");

            
            #line 75 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
                                                  if (!ModelState.IsValidField("confirmPassword")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 75 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
                                                                                                                                    }
            
            #line default
            #line hidden
WriteLiteral(">Confirm password</label> \r\n                    <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"confirmPassword\"");

WriteLiteral(" name=\"confirmPassword\"");

WriteAttribute("disabled", Tuple.Create(" disabled=\"", 3145), Tuple.Create("\"", 3166)
            
            #line 76 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
                 , Tuple.Create(Tuple.Create("", 3156), Tuple.Create<System.Object, System.Int32>(isSuccess
            
            #line default
            #line hidden
, 3156), false)
);

WriteLiteral(" ");

            
            #line 76 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
                                                                                                        Write(Validation.For("confirmPassword"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n");

WriteLiteral("                    ");

            
            #line 77 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
               Write(Html.ValidationMessage("confirmPassword"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li");

WriteLiteral(" class=\"reset-token\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"resetToken\"");

WriteLiteral(" ");

            
            #line 80 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
                                             if (!ModelState.IsValidField("resetToken")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 80 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
                                                                                                                          }
            
            #line default
            #line hidden
WriteLiteral(">Password reset token</label> \r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"resetToken\"");

WriteLiteral(" name=\"resetToken\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3563), Tuple.Create("\"", 3590)
            
            #line 81 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
, Tuple.Create(Tuple.Create("", 3571), Tuple.Create<System.Object, System.Int32>(passwordResetToken
            
            #line default
            #line hidden
, 3571), false)
);

WriteAttribute("disabled", Tuple.Create(" disabled=\"", 3591), Tuple.Create("\"", 3612)
            
            #line 81 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
                               , Tuple.Create(Tuple.Create("", 3602), Tuple.Create<System.Object, System.Int32>(isSuccess
            
            #line default
            #line hidden
, 3602), false)
);

WriteLiteral(" ");

            
            #line 81 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
                                                                                                                      Write(Validation.For("resetToken"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n");

WriteLiteral("                    ");

            
            #line 82 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
               Write(Html.ValidationMessage("resetToken"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ol>\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Reset password\"");

WriteAttribute("disabled", Tuple.Create(" disabled=\"", 3804), Tuple.Create("\"", 3825)
            
            #line 85 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
, Tuple.Create(Tuple.Create("", 3815), Tuple.Create<System.Object, System.Int32>(isSuccess
            
            #line default
            #line hidden
, 3815), false)
);

WriteLiteral("/>\r\n        </fieldset>\r\n    </form>\r\n");

            
            #line 88 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
} else {

            
            #line default
            #line hidden
WriteLiteral("    <p");

WriteLiteral(" class=\"message-info\"");

WriteLiteral(">\r\n        Password recovery is disabled for this website because the SMTP server" +
" is \r\n        not configured correctly. Please contact the owner of this site to" +
" reset \r\n        your password.\r\n    </p>\r\n");

            
            #line 94 "G:\Company\MensClothe\Account\PasswordReset.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
