#pragma checksum "G:\Company\MensClothe\Account\Thanks.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "24BD9E44D15CB720ED8445ED0F82F3F095FC3BCF"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Account_Thanks_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Account_Thanks_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "G:\Company\MensClothe\Account\Thanks.cshtml"
  
    // Set the layout page and page title
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Thanks for registering";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 7 "G:\Company\MensClothe\Account\Thanks.cshtml"
 if (!WebSecurity.IsAuthenticated) {

            
            #line default
            #line hidden
WriteLiteral("    <hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n        <h1>");

            
            #line 9 "G:\Company\MensClothe\Account\Thanks.cshtml"
       Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n        <h2>But you\'re not done yet!</h2>\r\n    </hgroup>\r\n");

            
            #line 12 "G:\Company\MensClothe\Account\Thanks.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n       An email with instructions on how to activate your account is on " +
"its way to you.\r\n    </p>\r\n");

            
            #line 16 "G:\Company\MensClothe\Account\Thanks.cshtml"
} else {

            
            #line default
            #line hidden
WriteLiteral("    <hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n        <h1>");

            
            #line 18 "G:\Company\MensClothe\Account\Thanks.cshtml"
       Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n        <h2>You are all set.</h2>\r\n    </hgroup>\r\n");

            
            #line 21 "G:\Company\MensClothe\Account\Thanks.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        It looks like you\'ve already confirmed your account and are good" +
" to go.\r\n    </p>\r\n");

            
            #line 25 "G:\Company\MensClothe\Account\Thanks.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
