#pragma checksum "G:\Company\MensClothe\Leather\LeatherResults.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8EDDB73EC3B92CA4D3BD7EC92AA229E4D98F92A0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Leather_LeatherResults_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Leather_LeatherResults_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

        $(document).ready(function () {

        });

        function SelectedItemClick(obj) {
            popupwin = window.open('DetailClotheResult' + ""?resultIndex="" + obj.id + ""&isPopup=1"", 'Detail', 'height=' + 600 + ',width=' + 520 + ',scrollbars=yes,left=400,top=300');
            popupwin.focus();
        }
    </script>

");

});

WriteLiteral("\r\n");

            
            #line 19 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Clothes";

    Database db;
    var items = new List<Clothe>();
    Database Dbase = new DbConnection("ConnectionStr").db;
  //  db = Database.OpenConnectionString(cstr.ConnectionString);
 //   db = Database.OpenConnectionString(cstr.ConnectionString, cstr.providerName);

     var ClotheRecords = Dbase.Query("SELECT * FROM  Clothe ");

    if (ClotheRecords != null)
    {
        foreach (var item in ClotheRecords)
        {
            items.Add(new Clothe { name = item["ItemName"], Price = Convert.ToString(item["Price"]), size = Convert.ToString(item["Size"]), Description = item["Description"], img = (Convert.ToString(item["ItemImage"])), quantity = Convert.ToString(item["QOH"]), ItemID = item["ItemID"] });

        }

    }
    
    if(IsPost)
    {
    
    if(Request.Form["ViewITem"]!= null)
    {
    
    
    
    }
    
    
    }
    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("    ");

            
            #line 58 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n\r\n    <fieldset>\r\n        <legend>Clothe Results </legend>\r\n        <div");

WriteLiteral(" id=\"detailform\"");

WriteLiteral("   ");

            
            #line 63 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
                                if (ClotheRecords == null)
                               {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 64 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
                                                                  }
            
            #line default
            #line hidden
WriteLiteral(@""">
            <table>
                <tr>
                    <td>
                        <label>
                            <b>Price</b></label>
                    </td>

                    <td>
                        <label for=""ItemImage"">
                            <b>Quantity</b>
                        </label>

                    </td>

                    <td>
                        <label for=""ItemImage"">
                            <b>Image</b>
                        </label>
                    </td>

                    <td>
                        <label>
                            <b>Size</b></label>
                    </td>
                    <td>
                        <label>
                            <b>Description</b></label>
                    </td>

                </tr>
");

            
            #line 95 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
                
            
            #line default
            #line hidden
            
            #line 95 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
                 foreach (var item in items)
                { 

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>\r\n                         " +
"   <label");

WriteLiteral(" id=\"Price\"");

WriteLiteral(">");

            
            #line 99 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
                                         Write(item.Price);

            
            #line default
            #line hidden
WriteLiteral(" </label>\r\n                        </td>\r\n                        <td>\r\n\r\n       " +
"                     <label");

WriteLiteral(" id=\"quantity\"");

WriteLiteral(">");

            
            #line 103 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
                                            Write(item.quantity);

            
            #line default
            #line hidden
WriteLiteral(" </label>\r\n                        </td>\r\n                        <td>\r\n         " +
"                      <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3132), Tuple.Create("\"", 3210)
            
            #line 106 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
, Tuple.Create(Tuple.Create("", 3138), Tuple.Create<System.Object, System.Int32>(MensClothe.AspControlUtil.getFullImagePath( Convert.ToString(item.img))
            
            #line default
            #line hidden
, 3138), false)
);

WriteLiteral(" alt=\"Red dot\"");

WriteLiteral(" width=\"100\"");

WriteLiteral(" height=\"150\"");

WriteLiteral(">\r\n                               ");

WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                  " +
"          <label");

WriteLiteral(" id=\"size\"");

WriteLiteral(">");

            
            #line 110 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
                                        Write(item.size);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        </td>\r\n                        <td>\r\n          " +
"                  <label");

WriteLiteral(" id=\"Desc\"");

WriteLiteral(">");

            
            #line 113 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
                                        Write(item.Description);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        </td>\r\n\r\n                        <td>\r\n        " +
"                    <input");

WriteAttribute("id", Tuple.Create(" id=\"", 3752), Tuple.Create("\"", 3769)
            
            #line 117 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
, Tuple.Create(Tuple.Create("", 3757), Tuple.Create<System.Object, System.Int32>(item.ItemID
            
            #line default
            #line hidden
, 3757), false)
);

WriteLiteral(" type=\"button\"");

WriteAttribute("name", Tuple.Create(" name=\"", 3784), Tuple.Create("\"", 3803)
            
            #line 117 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
, Tuple.Create(Tuple.Create("", 3791), Tuple.Create<System.Object, System.Int32>(item.ItemID
            
            #line default
            #line hidden
, 3791), false)
);

WriteLiteral("  \r\nonclick=\"SelectedItemClick(this);\"");

WriteLiteral("  value=\"View Detail Item\"");

WriteLiteral("  />\r\n                        </td>\r\n                        <td>\r\n              " +
"              <input");

WriteLiteral(" id=\"Add2Cart\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" name=\"Add2Cart\"");

WriteLiteral(" value=\"Add to Cart\"");

WriteLiteral("  />\r\n                        </td>\r\n\r\n                    </tr>\r\n");

            
            #line 125 "G:\Company\MensClothe\Leather\LeatherResults.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </table>\r\n        </div>\r\n    </fieldset>\r\n    <ul>\r\n        <li><a h" +
"ref=\"~/\">Home</a></li>\r\n        <li><a href=\"~/Admin/Admin\">Admin</a></li>\r\n    " +
"</ul>\r\n</form>\r\n");

        }
    }
}
