#pragma checksum "G:\Company\MensClothe\Admin\Admin.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A9C5EE96682E0467F41B4A3BF1BD4A4961ABE4B5"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Admin_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Admin_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral(" \r\n");

            
            #line 2 "G:\Company\MensClothe\Admin\Admin.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Admin Page";
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n <div");

WriteLiteral(" class=\"float-right\"");

WriteLiteral(">\r\n                    <section");

WriteLiteral(" id=\"login\"");

WriteLiteral(">\r\n");

            
            #line 11 "G:\Company\MensClothe\Admin\Admin.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 11 "G:\Company\MensClothe\Admin\Admin.cshtml"
                         if (WebSecurity.IsAuthenticated) {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 255), Tuple.Create("\"", 277)
, Tuple.Create(Tuple.Create("", 262), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Clothes")
, 262), false)
);

WriteLiteral(">Clothes</a>\r\n");

WriteLiteral("                                <ul>\r\n                                   <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 371), Tuple.Create("\"", 398)
, Tuple.Create(Tuple.Create("", 378), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Clothes/View")
, 378), false)
);

WriteLiteral(">View Item</a>    </li>\r\n                                   <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 465), Tuple.Create("\"", 495)
, Tuple.Create(Tuple.Create("", 472), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Clothes/AddItem")
, 472), false)
);

WriteLiteral(">Add Item</a>    </li>\r\n                                   <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 561), Tuple.Create("\"", 590)
, Tuple.Create(Tuple.Create("", 568), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Clothes/modify")
, 568), false)
);

WriteLiteral(">Update Item</a>    </li>\r\n                                   <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 659), Tuple.Create("\"", 688)
, Tuple.Create(Tuple.Create("", 666), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Clothes/delete")
, 666), false)
);

WriteLiteral(">Delete Item</a>    </li>\r\n                                </ul>\r\n");

WriteLiteral("                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 789), Tuple.Create("\"", 811)
, Tuple.Create(Tuple.Create("", 796), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Leather")
, 796), false)
);

WriteLiteral(">Leather</a>\r\n");

WriteLiteral("                                <ul>\r\n                                   <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 905), Tuple.Create("\"", 932)
, Tuple.Create(Tuple.Create("", 912), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Leather/View")
, 912), false)
);

WriteLiteral(">View Item</a>    </li>\r\n                                   <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 999), Tuple.Create("\"", 1025)
, Tuple.Create(Tuple.Create("", 1006), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Leather/add")
, 1006), false)
);

WriteLiteral(">Add Item</a>    </li>\r\n                                   <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1091), Tuple.Create("\"", 1120)
, Tuple.Create(Tuple.Create("", 1098), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Leather/modify")
, 1098), false)
);

WriteLiteral(">Update Item</a>    </li>\r\n                                   <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1189), Tuple.Create("\"", 1218)
, Tuple.Create(Tuple.Create("", 1196), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Leather/delete")
, 1196), false)
);

WriteLiteral(">Delete Item</a>    </li>\r\n                                </ul>\r\n");

WriteLiteral("                                 <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1320), Tuple.Create("\"", 1344)
, Tuple.Create(Tuple.Create("", 1327), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Cosmetics")
, 1327), false)
);

WriteLiteral(">Cosmetics</a>\r\n");

WriteLiteral("                                <ul>\r\n                                   <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1440), Tuple.Create("\"", 1469)
, Tuple.Create(Tuple.Create("", 1447), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Cosmetics/View")
, 1447), false)
);

WriteLiteral(">View Item</a>    </li>\r\n                                   <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1536), Tuple.Create("\"", 1564)
, Tuple.Create(Tuple.Create("", 1543), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Cosmetics/add")
, 1543), false)
);

WriteLiteral(">Add Item</a>    </li>\r\n                                   <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1630), Tuple.Create("\"", 1661)
, Tuple.Create(Tuple.Create("", 1637), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Cosmetics/modify")
, 1637), false)
);

WriteLiteral(">Update Item</a>    </li>\r\n                                   <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1730), Tuple.Create("\"", 1761)
, Tuple.Create(Tuple.Create("", 1737), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Cosmetics/delete")
, 1737), false)
);

WriteLiteral(">Delete Item</a>    </li>\r\n                                </ul>\r\n");

            
            #line 33 "G:\Company\MensClothe\Admin\Admin.cshtml"
                            
                           
                        } else {

                            Response.Redirect("~/Account/Login");
                            
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </section>\r\n                    \r\n     </div>\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
