#pragma checksum "G:\Company\MensClothe\PaymentPage.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "CDAA0FE753B0442A050E614387889C986E3CE6EC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_PaymentPage_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_PaymentPage_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "G:\Company\MensClothe\PaymentPage.cshtml"
  
    Page.Title = "Title goes here";
    //Layout = "Your Layout Page goes here";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div>\r\n    \r\n</div>");

        }
    }
}
