#pragma checksum "I:\Company\MensClothe\Products\DetailProductResult.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1FFF57C6EBA9CC2BC310F309BE6776F0F409FD69"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Products_DetailProductResult_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Products_DetailProductResult_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "I:\Company\MensClothe\Products\DetailProductResult.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Detail";
  //  dynamic ProductRecord = null;
    var Price = "";
    var quantity = "";
    var Description = "";
    var size = "";
    var clotheId = 0;
    Products db = new Products();
    var items = new List<SelectListItem>();
    string img = string.Empty; 
    var ms = new MemoryStream();
    var ClotheName = "";
    ProfileCommon profile = HttpContext.Current.Profile as ProfileCommon;
    if (Request.QueryString["resultIndex"] != null && !IsPost)
    {
        clotheId = int.Parse(Request.QueryString["resultIndex"]);
        Session.Add("resultIndex", clotheId);
       // db = Database.Open("mensClothe");
       Products    ProductRecord = Products.getProductDetail(clotheId);    // .QuerySingle("SELECT ItemName, Description, Price, QOH, Size, ItemImage FROM  Products Where ItemID=@0 ", clotheId);
        if (ProductRecord != null)
        {
            Price = Convert.ToString(ProductRecord.unitprice);
            Description = Convert.ToString(ProductRecord.Description);
            quantity = Convert.ToString(ProductRecord.quantity);
            size = Convert.ToString(ProductRecord.categoryID);
            img = Convert.ToString(ProductRecord.img);
            ClotheName = (Request.Form["ItemName"]);
        }
    }

    if (IsPost)
    {
        if (Request.Form["Add2Cart"] != null)
        {
         
       if(profile.SCart== null)
       {
           profile.SCart = new MensClothe.Cart();
       }
            
            
          profile.SCart.Insert(clotheId, double.Parse(Price), 1, ClotheName, img);
        //  Profile.Properties.
          //string prompt = "<script>$(document).ready(function(){{$.prompt('{0}!');}});</script>";
          //string message = string.Format(prompt, "This message is coming after postback.<br />Hello " + "added to the cart");
          //string javaScript = string.Format("ClientFunction('{0});", "message");
          //ScriptManager.RegisterStartupScript(this.Page, GetType(), "CallClientSideMethod", javaScript, true);
        //  string javaScript = string.Format("ClientFunction('{0});", "message");
         // this.Page.ClientScript.RegisterStartupScript(this.Page.GetType(), GetType(), "CallClientSideMethod", javaScript, true);

            
            #line default
            #line hidden
WriteLiteral("        <p>The is  ");

            
            #line 58 "I:\Company\MensClothe\Products\DetailProductResult.cshtml"
              Write(ClotheName);

            
            #line default
            #line hidden
WriteLiteral(" is added to the Shopping Cart</p>\r\n");

            
            #line 59 "I:\Company\MensClothe\Products\DetailProductResult.cshtml"
        Response.Write("<script>window.close();</" + "script>");





            
         // Server.Transfer("Products.aspx"); 
           
        }


    }
    
    
    
    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 79 "I:\Company\MensClothe\Products\DetailProductResult.cshtml"
   Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Delete Products Item</h2>\r\n</hgroup>\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral("  enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 84 "I:\Company\MensClothe\Products\DetailProductResult.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n    <fieldset>\r\n        <legend>Registration Form</legend>\r\n\r\n\r\n        <" +
"div");

WriteLiteral(" id=\"detailform\"");

WriteLiteral(">\r\n\r\n            <ol>\r\n                <li");

WriteLiteral(" class=\"Price\"");

WriteLiteral(">\r\n                    <label>\r\n                        Price</label>\r\n          " +
"          <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Price\"");

WriteLiteral(" name=\"Price\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3275), Tuple.Create("\"", 3289)
            
            #line 98 "I:\Company\MensClothe\Products\DetailProductResult.cshtml"
, Tuple.Create(Tuple.Create("", 3283), Tuple.Create<System.Object, System.Int32>(Price
            
            #line default
            #line hidden
, 3283), false)
);

WriteLiteral(" ) />\r\n                </li>\r\n                <li");

WriteLiteral(" class=\"ItemImage\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(">\r\n                        Quantity</label>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"quantity\"");

WriteLiteral(" name=\"quantity\"");

WriteAttribute("value", Tuple.Create("  value=\"", 3515), Tuple.Create("\"", 3533)
            
            #line 103 "I:\Company\MensClothe\Products\DetailProductResult.cshtml"
, Tuple.Create(Tuple.Create("", 3524), Tuple.Create<System.Object, System.Int32>(quantity
            
            #line default
            #line hidden
, 3524), false)
);

WriteLiteral(" />\r\n                </li>\r\n\r\n                <li");

WriteLiteral(" class=\"ItemImage\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(">\r\n                        Image\r\n                    </label>\r\n                 " +
"   <img");

WriteLiteral(" id=\"ItemImage\"");

WriteAttribute("src", Tuple.Create("   src=\"", 3749), Tuple.Create("\"", 3824)
            
            #line 110 "I:\Company\MensClothe\Products\DetailProductResult.cshtml"
, Tuple.Create(Tuple.Create("", 3757), Tuple.Create<System.Object, System.Int32>(MensClothe.AspControlUtil.getFullImagePath( Convert.ToString(img))
            
            #line default
            #line hidden
, 3757), false)
);

WriteLiteral(" alt=\"Red dot\"");

WriteLiteral(" width=\"100\"");

WriteLiteral(" height=\"150\"");

WriteLiteral(">\r\n                </li>\r\n\r\n                <li");

WriteLiteral(" class=\"Size\"");

WriteLiteral(">\r\n                    <label>\r\n                        Size</label>\r\n           " +
"         <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"size\"");

WriteLiteral(" name=\"size\"");

WriteAttribute("value", Tuple.Create("  value=\"", 4054), Tuple.Create("\"", 4068)
            
            #line 116 "I:\Company\MensClothe\Products\DetailProductResult.cshtml"
, Tuple.Create(Tuple.Create("", 4063), Tuple.Create<System.Object, System.Int32>(size
            
            #line default
            #line hidden
, 4063), false)
);

WriteLiteral(" />\r\n                </li>\r\n                <li");

WriteLiteral(" class=\"description\"");

WriteLiteral(">\r\n                    <label>\r\n                        Description</label>\r\n    " +
"                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Desc\"");

WriteLiteral(" name=\"Description\"");

WriteAttribute("value", Tuple.Create("  value=\"", 4280), Tuple.Create("\"", 4301)
            
            #line 121 "I:\Company\MensClothe\Products\DetailProductResult.cshtml"
, Tuple.Create(Tuple.Create("", 4289), Tuple.Create<System.Object, System.Int32>(Description
            
            #line default
            #line hidden
, 4289), false)
);

WriteLiteral(" />\r\n                </li>\r\n                <li");

WriteLiteral(" class=\"recaptcha\"");

WriteLiteral("></li>\r\n            </ol>\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"Add2Cart\"");

WriteLiteral(" name=\"Add2Cart\"");

WriteLiteral(" value=\"Add  to  Cart\"");

WriteLiteral(" />\r\n        </div>\r\n    </fieldset>\r\n\r\n    <ul>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4542), Tuple.Create("\"", 4551)
, Tuple.Create(Tuple.Create("", 4549), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 4549), false)
);

WriteLiteral(">Home</a></li>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4582), Tuple.Create("\"", 4602)
, Tuple.Create(Tuple.Create("", 4589), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Admin")
, 4589), false)
);

WriteLiteral(">Admin</a></li>\r\n    </ul>\r\n</form>\r\n");

        }
    }
}
