#pragma checksum "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1B83B789C38935FB9C3C60AD740E58013278A027"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Orders_ModifyOrders_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Orders_ModifyOrders_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Clothes";
    dynamic ProductRecord =null ;
    var Price = "";
    var quantity = "";
    var Description = "";
    var Itemname = "";
    var size = "";
    var clotheId = 0;
    var items = new List<SelectListItem>();
    var i = 0;
    var ms = new MemoryStream();
  //  byte[] imgArray= null;
    string imgArray = string.Empty;
    Products prd = new Products();
    
    Validation.RequireField("ItemName", "You must specify the  Products name.");
    Validation.RequireField("Price", "Price cannot be blank.");
    Validation.RequireField("ItemImage", "Choose Item Image");
    Validation.RequireField("Size", "Sizerequired ");

     if (IsPost)
     {
         var detailForm = Request.Form["detailform"];
         var updateDetail = Request.Form["UpdateDetail"];
         var updateConfirm = Request.Form["UpdateConfirm"];

  
         if (!string.IsNullOrEmpty(Request.Form["DDLid"]))
         {
           Session.Add("clotheId", Request.Form["DDLid"]) ;
         }

         if (updateDetail != null && Session["clotheId"] != null)
    {
            clotheId = int.Parse(Session["clotheId"].ToString());
         //   db = Database.Open("mensClothe");
           
            ProductRecord = Products.getProductDetail(clotheId);
            if(ProductRecord != null)
            {
                Price = Convert.ToString( ProductRecord["Price"]);
                Description = Convert.ToString(ProductRecord["Description"]);
                quantity =Convert.ToString( ProductRecord["QOH"]) ;
                size = Convert.ToString(ProductRecord["Size"]);
                imgArray = ProductRecord["ItemImage"];
                Itemname = ProductRecord["ItemName"];
            } 
    }
    else if (updateConfirm != null && Session["clotheId"] != null)
    {

       //ItemName = Request.Form["ItemName"];
       Price = Request.Form["Price"];
       // ItemImage = Request.Form["ItemImage"];
       quantity = Request.Form["quantity"];
       size =Request.Form["size"];
       Description = Request.Form["Description"];
       Itemname = Request.Form["pname"];
       HttpPostedFileBase file = Request.Files["ItemImage"];
       if (file != null)
       {
           ms = new MemoryStream();
           file.InputStream.CopyTo(ms);
           // imgStream = ms.ToArray();
       }

     //  System.Drawing.Bitmap image = new System.Drawing.Bitmap(ms);
    //   MemoryStream stream = new MemoryStream();
    //   image.Save(stream, System.Drawing.Imaging.ImageFormat.Bmp);
       var img = file.FileName;  //stream.ToArray();
        
       clotheId = int.Parse(Session["clotheId"].ToString());
      // db = Database.Open("mensClothe");
  //     i = Products.UpdateProduct(Itemname, Price, img, quantity, size, Description, clotheId);
       if (i == 0)
       {
           string url = "~/ErrorPage?ErrorMessage=" + "Dabse Error Occured";
           Response.Redirect(url);
       }
            
    
    }
    
    
     }
    
            // Insert a new item into the database
          //   db = Database.Open("mensClothe");

            // Check if user already exists
            List<Products> clotheRecords = Products.getProductRecodCollections();
             if (clotheRecords != null)
            {

               items.Add(new SelectListItem { Text = "Select....", Value = "" });
               foreach (var item in clotheRecords)
               {

                   items.Add(new SelectListItem { Text = item.name, Value = Convert.ToString( item.ItemID) });
                   
               }
            
            }
    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 116 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
   Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Delete Products Item</h2>\r\n</hgroup>\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral("  enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 121 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 123 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
Write(Html.ValidationSummary("Adding Products was unsuccessful. Please correct the errors and try again.", excludeFieldErrors: true, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <fieldset>\r\n        <legend>Registration Form</legend>\r\n        <ol>\r\n\r\n " +
"           <li");

WriteLiteral(" class=\"Clothes\"");

WriteLiteral(">\r\n                <label  >\r\n                    Select Products Item to be Dele" +
"ted:\r\n                </label>\r\n");

WriteLiteral("                ");

            
            #line 133 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
           Write(Html.DropDownList("DDLid",    items));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n\r\n            </li>\r\n             \r\n        </ol>\r\n   \r\n    <div");

WriteLiteral(" id=\"detailform\"");

WriteLiteral("   ");

            
            #line 142 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                            if(ProductRecord == null)
                           {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 143 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                                                              }
            
            #line default
            #line hidden
WriteLiteral("\">\r\n\r\n        <ol>    \r\n            \r\n           <li class=\"Price\">\r\n            " +
"    <label>\r\n                 Product Name</label>\r\n                <input type=" +
"\"text\" id=\"pname\" name=\"pname\" value=\"");

            
            #line 150 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                                                             Write(Itemname);

            
            #line default
            #line hidden
WriteLiteral("\" ) />\r\n                ");

WriteLiteral("\r\n              \r\n            </li>\r\n                    \r\n\r\n            <li clas" +
"s=\"Price\">\r\n                <label>\r\n                    Price</label>\r\n        " +
"        <input type=\"text\" id=\"Price\" name=\"Price\" value=\"");

            
            #line 159 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                                                             Write(Price);

            
            #line default
            #line hidden
WriteLiteral("\" ) />\r\n                ");

WriteLiteral("\r\n              \r\n            </li>\r\n            <li class=\"ItemImage\">\r\n        " +
"        <label for=\"ItemImage\">\r\n                    Quantity</label>\r\n         " +
"       <input type=\"text\" id=\"quantity\" name=\"quantity\"  value=\"");

            
            #line 166 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                                                                    Write(quantity);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            </li>\r\n\r\n\r\n            <li class=\"ItemImage\">\r\n");

            
            #line 171 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                
            
            #line default
            #line hidden
            
            #line 171 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                 if (imgArray!= null)
                {

            
            #line default
            #line hidden
WriteLiteral("                <label");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(">\r\n                    Image </label>\r\n");

WriteLiteral("                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 5851), Tuple.Create("\"", 5929)
            
            #line 175 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
, Tuple.Create(Tuple.Create("", 5857), Tuple.Create<System.Object, System.Int32>(MensClothe.AspControlUtil.getFullImagePath( Convert.ToString(imgArray))
            
            #line default
            #line hidden
, 5857), false)
);

WriteLiteral(" alt=\"Red dot\"");

WriteLiteral(" width=\"100\"");

WriteLiteral(" height=\"150\"");

WriteLiteral(">  \r\n");

            
            #line 176 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("             </li>\r\n             <li class=\"ItemImage\">\r\n\r\n                 <labe" +
"l for=\"ItemImage\">\r\n                 change   Image </label>\r\n                <l" +
"abel for=\"ItemImage\" ");

            
            #line 182 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                                        if(!ModelState.IsValidField("ItemImage")) {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 182 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                                                                                                                   }
            
            #line default
            #line hidden
WriteLiteral(">Image of the Products</label>\r\n                <input type=\"file\" id=\"ItemImage\"" +
" name=\"ItemImage\"  />\r\n                ");

WriteLiteral("\r\n              </li>\r\n\r\n           <li class=\"Size\">\r\n                <label>\r\n " +
"                   Size</label>\r\n                <input type=\"text\" id=\"size\" na" +
"me=\"size\"  value=\"");

            
            #line 190 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                                                            Write(size);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            </li>\r\n\r\n           \r\n            <li class=\"description\">\r\n   " +
"             <label>\r\n                    Description</label>\r\n                <" +
"input type=\"text\" id=\"Desc\" name=\"Description\"  value=\"");

            
            #line 197 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                                                                   Write(Description);

            
            #line default
            #line hidden
WriteLiteral(@""" />
            </li>
            <li class=""recaptcha""></li>
        </ol>
        <input type=""submit"" id=""UpdateConfirm"" name=""UpdateConfirm"" value=""Confirm"" />
       </div>
  </fieldset>
    <p>
    <input type=""submit"" id=""UpdateDetail""  name=""UpdateDetail"" value=""Update Products Item""  ");

            
            #line 205 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                                                                                               if (ProductRecord != null)
                            {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 206 "I:\Company\MensClothe\Admin\Orders\ModifyOrders.cshtml"
                                                               }
            
            #line default
            #line hidden
WriteLiteral("\" />\r\n   </p>\r\n    <ul>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7273), Tuple.Create("\"", 7282)
, Tuple.Create(Tuple.Create("", 7280), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 7280), false)
);

WriteLiteral(">Home</a></li>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7313), Tuple.Create("\"", 7333)
, Tuple.Create(Tuple.Create("", 7320), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Admin")
, 7320), false)
);

WriteLiteral(">Admin</a></li>\r\n        \r\n    </ul>\r\n</form>");

        }
    }
}
