#pragma checksum "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "83B81A09100A5E0500E2FBC84D482E3CFAF1B020"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Supplier_ModifySupplier_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Supplier_ModifySupplier_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Suppliers";
    dynamic SuppliersRecord = new DAL.Suppliers();
    var SuppID = 0;
    var items = new List<SelectListItem>();
    var i = 0;
    var ms = new MemoryStream();
    var email = "";
    
    DAL.Suppliers SuppliersDetails = new DAL.Suppliers();

    Validation.RequireField("txtCompanyName", "Supplier Name.");
    Validation.Add("txtCompanyName",
        Validator.StringLength(
            maxLength: Int32.MaxValue,
            minLength: 2,
            errorMessage: "Supplier Name Cannot be empty"));


    Validation.RequireField("txtName", "Contact Name.");
    Validation.Add("txtName",
        Validator.StringLength(
            maxLength: Int32.MaxValue,
            minLength: 2,
            errorMessage: "Contact Name Cannot be empty"));


    Validation.RequireField("txtCity", "Enter city Name.");
    Validation.Add("txtCity",
        Validator.StringLength(
            maxLength: Int32.MaxValue,
            minLength: 6,
            errorMessage: "City name cannot empty."));


    Validation.RequireField("txtState", "Enter state.");
    Validation.Add("txtState",
        Validator.StringLength(
            maxLength: Int32.MaxValue,
            minLength: 6,
            errorMessage: "Province name cannot empty."));

    Validation.RequireField("txtCountry", "Country Name required.");
    Validation.Add("txtCountry",
         Validator.StringLength(
             maxLength: Int32.MaxValue,
             minLength: 2,
             errorMessage: "Country Name required"));

    Validation.RequireField("txtAddress", "Enter your Address");
    Validation.Add("txtAddress",
        Validator.StringLength(
            maxLength: Int32.MaxValue,
            minLength: 6,
            errorMessage: "Enter detail address"));

    Validation.RequireField("txtEmail", "Enter Email Address");
    Validation.Add("txtEmail",
      Validator.Regex(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*",
      "Invalid format for an email address"));

    Validation.RequireField("txtPhone", "Enter Phone Number");
    Validation.Add("txtPhone",
    Validator.StringLength(maxLength: Int32.MaxValue,
            minLength: 10, errorMessage: "Must be between 10 and 20"));

    if (IsPost)
    {
        var detailForm = Request.Form["detailform"];
        var updateDetail = Request.Form["UpdateDetail"];
        var updateConfirm = Request.Form["UpdateConfirm"];



        if (!string.IsNullOrEmpty(Request.Form["DDLid"]))
        {
            Session.Add("SuppID", Request.Form["DDLid"]);
        }

        if (updateDetail != null && Session["SuppID"] != null)
        {

            SuppID = int.Parse(Session["SuppID"].ToString());
            SuppliersRecord = DAL.Suppliers.getSuppliersDetail(SuppID);
            
if(SuppliersRecord!=null )
{

    email = SuppliersRecord.Email;

}
            
            
            
        }
        else if (updateConfirm != null && Session["SuppID"] != null)
        {


            SuppliersDetails = new DAL.Suppliers
            {
                contactname = Request.Form["txtName"].ToString(),
                address = Request.Form["txtAddress"].ToString(),
                city = Request.Form["txtCity"].ToString(),
                country = Request.Form["txtCountry"].ToString(),
                Email = Request.Form["txtEmail"].ToString(),
                phone = Request.Form["txtPhone"].ToString(),
                region = Request.Form["txtState"].ToString(),
                postalcode = Request.Form["txtZip"].ToString(),
                companyname = Request.Form["txtCompanyName"].ToString(),
                supplierid = int.Parse(Session["SuppID"].ToString())

            };


            if (Validation.IsValid())
            {


                i = DAL.Suppliers.UpdateSuppliers(SuppliersDetails); //Products.UpdateProduct(Itemname, Price, img, quantity, size, Description, clotheId);
                if (i == 0)
                {
                    string url = "~/ErrorPage?ErrorMessage=" + "Dabse Error Occured";
                    Response.Redirect(url);
                }
            }




        }


    }

    // Check if user already exists
    List<DAL.Suppliers> SuppliersRecords = DAL.Suppliers.getAllSuppliers();
    if (SuppliersRecords != null)
    {

        items.Add(new SelectListItem { Text = "Select....", Value = "" });
        foreach (var item in SuppliersRecords)
        {

            items.Add(new SelectListItem { Text = item.companyname, Value = Convert.ToString(item.supplierid) });

        }

    }
    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n\r\n    <h1>Update Supplier</h1>\r\n</hgroup>\r\n<section>\r\n    <form");

WriteLiteral(" method=\"post\"");

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 166 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
   Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");

WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 168 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
   Write(Html.ValidationSummary("Adding Products was unsuccessful. Please correct the errors and try again.", excludeFieldErrors: true, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <fieldset>\r\n\r\n            <legend>Modyfy Supplier</legend>\r\n           " +
" <ol>\r\n\r\n                <li");

WriteLiteral(" class=\"Clothes\"");

WriteLiteral(">\r\n                    <label>\r\n                        Select Supplier to update" +
" :\r\n                    </label>\r\n");

WriteLiteral("                    ");

            
            #line 178 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
               Write(Html.DropDownList("DDLid", items));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n\r\n                </li>\r\n\r\n            </ol>\r\n\r\n            <div");

WriteLiteral(" id=\"detailform\"");

WriteLiteral("   ");

            
            #line 187 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                    if (SuppliersRecord.supplierid == 0)
                                   {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 188 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                      }
            
            #line default
            #line hidden
WriteLiteral("   >\r\n                <ol>\r\n                    <li>\r\n\r\n                        <" +
"label");

WriteLiteral(" for=\"txtCompanyName\"");

WriteLiteral(" ");

            
            #line 192 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                     if (!ModelState.IsValidField("txtCompanyName"))
                                                     {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("class=\"error-label\"");

            
            #line 193 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                       }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            Company  Name:\r\n                    \r\n            " +
"            </label>\r\n                    </li>\r\n                    <li>\r\n     " +
"                   <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtCompanyName\"");

WriteLiteral(" name=\"txtCompanyName\"");

WriteLiteral(" \'");

            
            #line 199 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                 Write(Validation.For("txtCompanyName"));

            
            #line default
            #line hidden
WriteLiteral("\' value=\"");

            
            #line 199 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                                                           Write(SuppliersRecord.companyname);

            
            #line default
            #line hidden
WriteLiteral("\"  />\r\n");

WriteLiteral("                        ");

            
            #line 200 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                   Write(Html.ValidationMessage("txtCompanyName"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                </ol>\r\n\r\n                <ol>\r\n     " +
"               <li>\r\n                        <label");

WriteLiteral(" for=\"txtName\"");

WriteLiteral(" ");

            
            #line 206 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                              if (!ModelState.IsValidField("txtName"))
                                              {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("class=\"error-label\"");

            
            #line 207 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            ContactName:\r\n                        </label>\r\n  " +
"                  </li>\r\n                    <li>\r\n\r\n                        <in" +
"put");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtName\"");

WriteLiteral(" name=\"txtName\"");

WriteLiteral(" \'");

            
            #line 213 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                   Write(Validation.For("txtName"));

            
            #line default
            #line hidden
WriteLiteral("\' value=\"");

            
            #line 213 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                                      Write(SuppliersRecord.contactname);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");

WriteLiteral("                        ");

            
            #line 214 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                   Write(Html.ValidationMessage("txtName"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                </ol>\r\n                <ol>\r\n       " +
"             <li>\r\n                        <label");

WriteLiteral(" for=\"txtAddress\"");

WriteLiteral(" ");

            
            #line 219 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                 if (!ModelState.IsValidField("txtAddress"))
                                                 {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("class=\"error-label\"");

            
            #line 220 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                   }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            Address:\r\n                        </label>\r\n      " +
"              </li>\r\n                    <li>\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtAddress\"");

WriteLiteral(" name=\"txtAddress\"");

WriteLiteral(" \'");

            
            #line 225 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                         Write(Validation.For("txtAddress"));

            
            #line default
            #line hidden
WriteLiteral("\' value=\"");

            
            #line 225 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                                               Write(SuppliersRecord.address);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");

WriteLiteral("                        ");

            
            #line 226 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                   Write(Html.ValidationMessage("txtAddress"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                </ol>\r\n                <ol>\r\n       " +
"             <li>\r\n                        <label");

WriteLiteral(" for=\"txtCity\"");

WriteLiteral(" ");

            
            #line 231 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                              if (!ModelState.IsValidField("txtCity"))
                                              {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("class=\"error-label\"");

            
            #line 232 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            City:\r\n                        </label>\r\n         " +
"           </li>\r\n                    <li>\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtCity\"");

WriteLiteral(" name=\"txtCity\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8165), Tuple.Create("\"", 8194)
            
            #line 237 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
, Tuple.Create(Tuple.Create("", 8173), Tuple.Create<System.Object, System.Int32>(SuppliersRecord.city
            
            #line default
            #line hidden
, 8173), false)
);

WriteLiteral(" \'");

            
            #line 237 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                                 Write(Validation.For("txtCity"));

            
            #line default
            #line hidden
WriteLiteral("\' />\r\n");

WriteLiteral("                        ");

            
            #line 238 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                   Write(Html.ValidationMessage("txtCity"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                </ol>\r\n                <ol>\r\n       " +
"             <li>\r\n                        <label");

WriteLiteral(" for=\"txtState\"");

WriteLiteral(" ");

            
            #line 243 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                               if (!ModelState.IsValidField("txtState"))
                                               {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("class=\"error-label\"");

            
            #line 244 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                 }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            State/Province:\r\n                        </label>\r" +
"\n                    </li>\r\n                    <li>\r\n                        <i" +
"nput");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtState\"");

WriteLiteral(" name=\"txtState\"");

WriteLiteral(" \'");

            
            #line 249 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                     Write(Validation.For("txtState"));

            
            #line default
            #line hidden
WriteLiteral("\' value=\"");

            
            #line 249 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                                         Write(SuppliersRecord.region);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                        &nbsp;&nbsp; \r\n");

WriteLiteral("                          ");

            
            #line 251 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                     Write(Html.ValidationMessage("txtState"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                </ol>\r\n                <ol>\r\n       " +
"             <li>\r\n                        <label");

WriteLiteral(" for=\"txtZip\"");

WriteLiteral(" ");

            
            #line 256 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                             if (!ModelState.IsValidField("txtZip"))
                                            {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 257 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                             }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            Zip/Postal Code:\r\n                        </label>" +
"\r\n                    </li>\r\n                    <li>\r\n                        <" +
"input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtZip\"");

WriteLiteral(" name=\"txtZip\"");

WriteLiteral(" \'");

            
            #line 262 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                 Write(Validation.For("txtZip"));

            
            #line default
            #line hidden
WriteLiteral("\' value=\"");

            
            #line 262 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                                   Write(SuppliersRecord.postalcode);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");

WriteLiteral("                        ");

            
            #line 263 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                   Write(Html.ValidationMessage("txtZip"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                </ol>\r\n                <ol>\r\n       " +
"             <li>\r\n                        <label");

WriteLiteral(" for=\"txtCountry\"");

WriteLiteral(" ");

            
            #line 268 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                 if (!ModelState.IsValidField("txtCountry"))
                                                {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 269 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                 }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            Country:\r\n                        </label>\r\n      " +
"              </li>\r\n                    <li>\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtCountry\"");

WriteLiteral(" name=\"txtCountry\"");

WriteLiteral(" \'");

            
            #line 274 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                         Write(Validation.For("txtCountry"));

            
            #line default
            #line hidden
WriteLiteral("\' value=\"");

            
            #line 274 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                                               Write(SuppliersRecord.country);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");

WriteLiteral("                        ");

            
            #line 275 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                   Write(Html.ValidationMessage("txtCountry"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                </ol>\r\n                <ol>\r\n       " +
"             <li>\r\n                        <label");

WriteLiteral(" for=\"txtEmail\"");

WriteLiteral(" ");

            
            #line 280 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                               if (!ModelState.IsValidField("txtEmail"))
                                              {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("class=\"error-label\"");

            
            #line 281 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            Email:\r\n                        </label>\r\n        " +
"            </li>\r\n                    <li>\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtEmail\"");

WriteLiteral(" name=\"txtEmail\"");

WriteLiteral(" \'");

            
            #line 286 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                     Write(Validation.For("txtEmail"));

            
            #line default
            #line hidden
WriteLiteral("\' value= \"");

            
            #line 286 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                                          Write(email.Trim());

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");

WriteLiteral("                        ");

            
            #line 287 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                   Write(Html.ValidationMessage("txtEmail"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                </ol>\r\n                <ol>\r\n       " +
"             <li>\r\n                        <label");

WriteLiteral(" for=\"txtPhone\"");

WriteLiteral(" ");

            
            #line 292 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                               if (!ModelState.IsValidField("txtPhone"))
                                              {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("class=\"error-label\"");

            
            #line 293 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            Phone:\r\n                        </label>\r\n        " +
"            </li>\r\n                    <li>\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtPhone\"");

WriteLiteral(" name=\"txtPhone\"");

WriteLiteral("  \'");

            
            #line 298 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                      Write(Validation.For("txtPhone"));

            
            #line default
            #line hidden
WriteLiteral("\'  value=\"");

            
            #line 298 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                                           Write(SuppliersRecord.phone);

            
            #line default
            #line hidden
WriteLiteral("\"  />\r\n");

WriteLiteral("                        ");

            
            #line 299 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                   Write(Html.ValidationMessage("txtPhone"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                </ol>\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"UpdateConfirm\"");

WriteLiteral(" name=\"UpdateConfirm\"");

WriteLiteral(" value=\"Confirm\"");

WriteLiteral(" />\r\n\r\n            </div>\r\n        </fieldset>\r\n\r\n        <p>\r\n            <input" +
"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"UpdateDetail\"");

WriteLiteral("  name=\"UpdateDetail\"");

WriteLiteral(" value=\"Update Suppliers\"");

WriteLiteral("  ");

            
            #line 308 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                                   if (SuppliersRecord.supplierid != 0)
                                                                                                  {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 309 "I:\Company\MensClothe\Admin\Supplier\ModifySupplier.cshtml"
                                                                                                                                     }
            
            #line default
            #line hidden
WriteLiteral(" />\r\n        </p>\r\n        <ul>\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 11850), Tuple.Create("\"", 11859)
, Tuple.Create(Tuple.Create("", 11857), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 11857), false)
);

WriteLiteral(">Home</a></li>\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 11894), Tuple.Create("\"", 11914)
, Tuple.Create(Tuple.Create("", 11901), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Admin")
, 11901), false)
);

WriteLiteral(">Admin</a></li>\r\n\r\n        </ul>\r\n    </form>\r\n</section>\r\n");

        }
    }
}
