#pragma checksum "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "31914C3E0CA51900D356B42F2BA01CAAB8155381"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Supplier_ViewSupplier_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Supplier_ViewSupplier_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 86), Tuple.Create("\"", 124)
, Tuple.Create(Tuple.Create("", 92), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 92), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 148), Tuple.Create("\"", 198)
, Tuple.Create(Tuple.Create("", 154), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 154), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n        $(document).ready(function () {\r\n\r\n        });\r\n\r\n    </script>\r\n\r\n");

});

WriteLiteral("\r\n\r\n\r\n\r\n");

            
            #line 19 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Suppliers";
    List<DAL.Suppliers> SuppliersRecords = new List<DAL.Suppliers>();
    var items = new List<DAL.Suppliers>();
    SuppliersRecords = DAL.Suppliers.getAllSuppliers();
       

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("    ");

            
            #line 32 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n    <div");

WriteLiteral(" id=\"detailform\"");

WriteLiteral("   ");

            
            #line 34 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
                            if (SuppliersRecords == null)
                           {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 35 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
                                                              }
            
            #line default
            #line hidden
WriteLiteral("\">\r\n\r\n\r\n\r\n        <table>\r\n\r\n");

            
            #line 41 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
            
            
            #line default
            #line hidden
            
            #line 41 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
             foreach (var item in SuppliersRecords)
            { 

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n                        <label>\r\n" +
"                         Supplier Name:\r\n                        </label>\r\n     " +
"                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtCompanyname\"");

WriteLiteral(" name=\"txtName\"");

WriteAttribute("value", Tuple.Create("  value=\"", 1173), Tuple.Create("\"", 1199)
            
            #line 48 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
       , Tuple.Create(Tuple.Create("", 1182), Tuple.Create<System.Object, System.Int32>(item.companyname
            
            #line default
            #line hidden
, 1182), false)
);

WriteLiteral(" />\r\n\r\n                        <label>\r\n                         Contact   Name:\r" +
"\n                        </label>\r\n                         <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtName\"");

WriteLiteral(" name=\"txtName\"");

WriteAttribute("value", Tuple.Create("  value=\"", 1387), Tuple.Create("\"", 1413)
            
            #line 53 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
, Tuple.Create(Tuple.Create("", 1396), Tuple.Create<System.Object, System.Int32>(item.contactname
            
            #line default
            #line hidden
, 1396), false)
);

WriteLiteral(" />\r\n                        <label");

WriteLiteral(" for=\"txtAddress\"");

WriteLiteral(">\r\n                            Address:\r\n                        </label>\r\n      " +
"                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtAddress\"");

WriteLiteral(" name=\"txtAddress\"");

WriteAttribute("value", Tuple.Create("  value=\"", 1619), Tuple.Create("\"", 1641)
            
            #line 57 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
       , Tuple.Create(Tuple.Create("", 1628), Tuple.Create<System.Object, System.Int32>(item.address
            
            #line default
            #line hidden
, 1628), false)
);

WriteLiteral("   />\r\n                       \r\n                         <label");

WriteLiteral(" for=\"txtCity\"");

WriteLiteral(">\r\n                            City:\r\n                        </label>\r\n         " +
"                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtCity\"");

WriteLiteral(" name=\"txtCity\"");

WriteAttribute("value", Tuple.Create("   value=\"", 1862), Tuple.Create("\"", 1882)
            
            #line 62 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
 , Tuple.Create(Tuple.Create("", 1872), Tuple.Create<System.Object, System.Int32>(item.city
            
            #line default
            #line hidden
, 1872), false)
);

WriteLiteral(" />\r\n                       \r\n                        <label");

WriteLiteral(" for=\"txtState\"");

WriteLiteral(">\r\n                            State/Province:\r\n                        </label>\r" +
"\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtState\"");

WriteLiteral(" name=\"txtState\"");

WriteAttribute("value", Tuple.Create("  value=\"", 2112), Tuple.Create("\"", 2133)
            
            #line 67 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
 , Tuple.Create(Tuple.Create("", 2121), Tuple.Create<System.Object, System.Int32>(item.region
            
            #line default
            #line hidden
, 2121), false)
);

WriteLiteral(" />\r\n                        &nbsp;&nbsp; \r\n                       \r\n            " +
"             <label");

WriteLiteral(" for=\"ZipCode\"");

WriteLiteral(">\r\n                            Zip/Postal Code:\r\n                        </label>" +
"\r\n                         <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtZip\"");

WriteLiteral(" name=\"txtZip\"");

WriteAttribute("value", Tuple.Create("  value=\"", 2400), Tuple.Create("\"", 2425)
            
            #line 73 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
, Tuple.Create(Tuple.Create("", 2409), Tuple.Create<System.Object, System.Int32>(item.postalcode
            
            #line default
            #line hidden
, 2409), false)
);

WriteLiteral(" />\r\n                       \r\n                        <label>Country:</label>\r\n  " +
"                       <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Country\"");

WriteLiteral(" name=\"txtZip\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2575), Tuple.Create("\"", 2596)
            
            #line 76 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
, Tuple.Create(Tuple.Create("", 2583), Tuple.Create<System.Object, System.Int32>(item.country
            
            #line default
            #line hidden
, 2583), false)
);

WriteLiteral(" />\r\n                       \r\n                        <label");

WriteLiteral(" for=\"txtEmail\"");

WriteLiteral(">\r\n                            Email:\r\n                        </label>\r\n        " +
"                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtEmail\"");

WriteLiteral(" name=\"txtEmail\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2817), Tuple.Create("\"", 2836)
            
            #line 81 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
, Tuple.Create(Tuple.Create("", 2825), Tuple.Create<System.Object, System.Int32>(item.Email
            
            #line default
            #line hidden
, 2825), false)
);

WriteLiteral(" />\r\n                        <label");

WriteLiteral(" for=\"txtPhone\"");

WriteLiteral(">\r\n                            Phone:\r\n                        </label>\r\n        " +
"                  <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtPhone\"");

WriteLiteral(" name=\"txtPhone\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3034), Tuple.Create("\"", 3053)
            
            #line 85 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
  , Tuple.Create(Tuple.Create("", 3042), Tuple.Create<System.Object, System.Int32>(item.phone
            
            #line default
            #line hidden
, 3042), false)
);

WriteLiteral(" />\r\n\r\n                    </td>\r\n                    <td>\r\n \r\n                  " +
"  </td>\r\n                </tr>\r\n");

            
            #line 92 "I:\Company\MensClothe\Admin\Supplier\ViewSupplier.cshtml"
          
           
        
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </div>\r\n    <ul>\r\n        <li><a href=\"~/\">Home</a></li>\r\n " +
"       <li><a href=\"~/Admin/Admin\">Admin</a></li>\r\n    </ul>\r\n</form>\r\n");

        }
    }
}
