#pragma checksum "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "056256846E854D5A9D4B8BE2409FAE1FB738013E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Customer_ModifyCustomer_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Customer_ModifyCustomer_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Clothes";
    dynamic CustomerRecord = null;
    var cusId = 0;
    var items = new List<SelectListItem>();
    var i = 0;
    var ms = new MemoryStream();
    DAL.Customer CustomerDetails = new DAL.Customer();
    
    Validation.RequireField("txtName", "Enter your Name.");
    Validation.Add("txtName",
        Validator.StringLength(
            maxLength: Int32.MaxValue,
            minLength: 2,
            errorMessage: "Name Cannot be empty"));

    Validation.RequireField("txtCity", "Enter city Name.");
    Validation.Add("txtCity",
        Validator.StringLength(
            maxLength: Int32.MaxValue,
            minLength: 6,
            errorMessage: "City name cannot empty."));

    Validation.RequireField("txtCC", "Enter card number.");
    Validation.Add("txtCC",
        Validator.StringLength(
            maxLength: 16,
            minLength: 16,
            errorMessage: "Credit Card number must be 16 characters ."));


    Validation.RequireField("txtState", "Enter state.");
    Validation.Add("txtState",
        Validator.StringLength(
            maxLength: Int32.MaxValue,
            minLength: 6,
            errorMessage: "Province name cannot empty."));

    Validation.RequireField("txtAddress", "Enter your Address");
    Validation.Add("txtAddress",
        Validator.StringLength(
            maxLength: Int32.MaxValue,
            minLength: 6,
            errorMessage: "Enter detail address"));

    Validation.RequireField("txtEmail", "Enter Email Address");
    Validation.Add("txtEmail",
      Validator.Regex(@"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$",
      "Invalid format for an email address"));

    Validation.RequireField("txtPhone", "Enter Phone Number");
    Validation.Add("txtPhone",
    Validator.StringLength(maxLength: Int32.MaxValue,
            minLength: 10, errorMessage: "Must be between 10 and 20"));

    //Validation.RequireField("txtSecurity", "Enter Security code");
    Validation.Add("txtSecurity",
        Validator.Required("Must be three numbers"));

    if (IsPost)
    {
        var detailForm = Request.Form["detailform"];
        var updateDetail = Request.Form["UpdateDetail"];
        var updateConfirm = Request.Form["UpdateConfirm"];


        if (!string.IsNullOrEmpty(Request.Form["DDLid"]))
        {
            Session.Add("cusId", Request.Form["DDLid"]);
        }

        if (updateDetail != null && Session["cusId"] != null)
        {
            //cusId
            cusId =int.Parse( Session["cusId"].ToString());

            CustomerRecord = DAL.Customer.getCustomerDetail(cusId);
        }
        else if (updateConfirm != null && Session["cusId"] != null)
        {

            CustomerDetails = new DAL.Customer
            {
                customername = Request.Form["txtName"].ToString(),
                Address = Request.Form["txtAddress"].ToString(),
                City = Request.Form["txtCity"].ToString(),
                Country = Request.Form["txtCountryId"].ToString(),
                Email = Request.Form["txtEmail"].ToString(),
                phone = Request.Form["txtPhone"].ToString(),
                State = Request.Form["txtState"].ToString(),
                Zipcode = Request.Form["txtZip"].ToString(),
                CustomerID = Session["cusId"].ToString()

            };





            i = DAL.Customer.UpdateCustomer(CustomerDetails); //Products.UpdateProduct(Itemname, Price, img, quantity, size, Description, clotheId);
            if (i == 0)
            {
                string url = "~/ErrorPage?ErrorMessage=" + "Dabse Error Occured";
                Response.Redirect(url);
            }


        }


    }

    // Check if user already exists
    List<DAL.Customer> CustomerRecords = DAL.Customer.getAllCustomers();
    if (CustomerRecords != null)
    {

        items.Add(new SelectListItem { Text = "Select....", Value = "" });
        foreach (var item in CustomerRecords)
        {

            items.Add(new SelectListItem { Text = item.customername, Value = Convert.ToString(item.CustomerID) });

        }

    }
    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 138 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
   Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Delete Products Item</h2>\r\n</hgroup>\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 143 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 145 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
Write(Html.ValidationSummary("Adding Products was unsuccessful. Please correct the errors and try again.", excludeFieldErrors: true, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <fieldset>\r\n        <legend>Registration Form</legend>\r\n        <ol>\r\n\r\n " +
"           <li");

WriteLiteral(" class=\"Clothes\"");

WriteLiteral(">\r\n                <label>\r\n                    Select Products Item to be Delete" +
"d:\r\n                </label>\r\n");

WriteLiteral("                ");

            
            #line 155 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
           Write(Html.DropDownList("DDLid", items));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n\r\n            </li>\r\n\r\n        </ol>\r\n\r\n        <div");

WriteLiteral(" id=\"detailform\"");

WriteLiteral("   ");

            
            #line 164 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
                                if (CustomerDetails != null)
                               {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 165 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
                                                                  }
            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <table>\r\n                <tr>\r\n                    <td>\r\n        " +
"                <label>\r\n                            Name:\r\n                    " +
"    </label>\r\n                        <input type=\"text\" id=\"txtName\" name=\"txtN" +
"ame\"  value=\"");

            
            #line 172 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
                                                                          Write(CustomerDetails.customername);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                        <label for=\"txtAddress\">\r\n                         " +
"   Address:\r\n                        </label>\r\n                        <input ty" +
"pe=\"text\" id=\"txtAddress\" name=\"txtAddress\"  value=\"");

            
            #line 176 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
                                                                                Write(CustomerDetails.Address);

            
            #line default
            #line hidden
WriteLiteral("\"   />\r\n\r\n                        <label for=\"txtCity\">\r\n                        " +
"    City:\r\n                        </label>\r\n                        <input type" +
"=\"text\" id=\"txtCity\" name=\"txtCity\"   value=\"");

            
            #line 181 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
                                                                           Write(CustomerDetails.City);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\r\n                        <label for=\"txtState\">\r\n                         " +
"   State/Province:\r\n                        </label>\r\n                        <i" +
"nput type=\"text\" id=\"txtState\" name=\"txtState\"  value=\"");

            
            #line 186 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
                                                                            Write(CustomerDetails.State);

            
            #line default
            #line hidden
WriteLiteral(@""" />
                        &nbsp;&nbsp; 
                       
                         <label for=""ZipCode"">
                             Zip/Postal Code:
                         </label>
                        <input type=""text"" id=""txtZip"" name=""txtZip""  value=""");

            
            #line 192 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
                                                                        Write(CustomerDetails.Zipcode);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\r\n                        <label>Country:</label>\r\n                        " +
"<input type=\"text\" id=\"Country\" name=\"txtZip\" value=\"");

            
            #line 195 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
                                                                        Write(CustomerDetails.Country);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\r\n                        <label for=\"txtEmail\">\r\n                         " +
"   Email:\r\n                        </label>\r\n                        <input type" +
"=\"text\" id=\"txtEmail\" name=\"txtEmail\" value=\"");

            
            #line 200 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
                                                                           Write(CustomerDetails.Email);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                        <label for=\"txtPhone\">\r\n                           " +
" Phone:\r\n                        </label>\r\n                        <input type=\"" +
"text\" id=\"txtPhone\" name=\"txtPhone\" value=\"");

            
            #line 204 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
                                                                           Write(CustomerDetails.phone);

            
            #line default
            #line hidden
WriteLiteral(@""" />

                    </td>
                    <td></td>
                </tr>


            </table>
            <input type=""submit"" id=""UpdateConfirm"" name=""UpdateConfirm"" value=""Confirm"" />
        </div>
    </fieldset>
    <p>
        <input type=""submit"" id=""UpdateDetail""  name=""UpdateDetail"" value=""Update Customer""  ");

            
            #line 216 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
                                                                                              if (CustomerRecord != null)
                                                                                             {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 217 "I:\Company\MensClothe\Admin\Customer\ModifyCustomer.cshtml"
                                                                                                                                }
            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    </p>\r\n    <ul>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7777), Tuple.Create("\"", 7786)
, Tuple.Create(Tuple.Create("", 7784), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 7784), false)
);

WriteLiteral(">Home</a></li>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7817), Tuple.Create("\"", 7837)
, Tuple.Create(Tuple.Create("", 7824), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Admin")
, 7824), false)
);

WriteLiteral(">Admin</a></li>\r\n\r\n    </ul>\r\n</form>\r\n");

        }
    }
}
