#pragma checksum "I:\Company\MensClothe\Default.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "CF7FCF163077F5796F72269F0FB683A7C4E55CFE"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Default_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Default_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "I:\Company\MensClothe\Default.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Home Page";

    
    
    // Initialize general page variables
    var email = "";
    var password = "";
    var confirmPassword = "";

 

    // If this is a POST request, validate and process data
    if (IsPost) {
        AntiForgery.Validate();
        email = Request.Form["email"];
        password = Request.Form["password"];
        confirmPassword = Request.Form["confirmPassword"];

        // Validate the user's captcha answer
        // if (!ReCaptcha.Validate("PRIVATE_KEY")) {
        //     ModelState.AddError("recaptcha", "Captcha response was not correct");
        // }

        // If all information is valid, create a new account
        if (Validation.IsValid()) {
            // Insert a new user into the database
            var db = Database.Open("mensClothe");

            // Check if user already exists
            var user = db.QuerySingle("SELECT Email FROM UserProfile WHERE LOWER(Email) = LOWER(@0)", email);
            if (user == null) {
                // Insert email into the profile table
                db.Execute("INSERT INTO UserProfile (Email) VALUES (@0)", email);

                // Create and associate a new entry in the membership database.
                // If successful, continue processing the request
                try {
                    bool requireEmailConfirmation = !WebMail.SmtpServer.IsEmpty();
                    var token = WebSecurity.CreateAccount(email, password, requireEmailConfirmation);
                    if (requireEmailConfirmation) {
                        var hostUrl = Request.Url.GetComponents(UriComponents.SchemeAndServer, UriFormat.Unescaped);
                        var confirmationUrl = hostUrl + VirtualPathUtility.ToAbsolute("~/Account/Confirm?confirmationCode=" + HttpUtility.UrlEncode(token));

                        WebMail.Send(
                            to: email,
                            subject: "Please confirm your account",
                            body: "Your confirmation code is: " + token + ". Visit <a href=\"" + confirmationUrl + "\">" + confirmationUrl + "</a> to activate your account."
                        );
                    }

                    if (requireEmailConfirmation) {
                        // Thank the user for registering and let them know an email is on its way
                        Response.Redirect("~/Account/Thanks");
                    } else {
                        // Navigate back to the homepage and exit
                        WebSecurity.Login(email, password);

                        Response.Redirect("~/");
                    }
                } catch (System.Web.Security.MembershipCreateUserException e) {
                    ModelState.AddFormError(e.Message);
                }
            } else {
                // User already exists
                ModelState.AddFormError("Email address is already in use.");
            }
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n \r\n \r\n\r\n");

DefineSection("featured", () => {

WriteLiteral("\r\n<section");

WriteLiteral(" class=\"featured\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n        <hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n            <h1>");

            
            #line 80 "I:\Company\MensClothe\Default.cshtml"
           Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n            <h2>Men\'s Online Store</h2>\r\n        </hgroup>\r\n      \r\n     " +
"   <p>\r\n             <input");

WriteLiteral(" id=\"search\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"search item\"");

WriteLiteral(" />   <input");

WriteLiteral(" id=\"searchBox\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("   />\r\n        </p>\r\n    </div>\r\n</section>\r\n");

});

WriteLiteral("\r\n<h3>We suggest the following:</h3>\r\n\r\n<ol");

WriteLiteral(" class=\"round\"");

WriteLiteral(">\r\n    <li");

WriteLiteral(" class=\"one\"");

WriteLiteral(@">
        <h5>Getting Started</h5>
        ASP.NET Web Pages and the new Razor syntax provide a fast, approachable, and lightweight way to combine server code with HTML
        to create dynamic web content. Connect to databases, add video, link to social networking sites, and include many more features
        that let you create beautiful sites using the latest web standards.
        <a");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=245139\"");

WriteLiteral(">Learn more…</a>\r\n    </li>\r\n\r\n    <li");

WriteLiteral(" class=\"two\"");

WriteLiteral(">\r\n        <h5>Add NuGet packages and jump start your coding</h5>\r\n        NuGet " +
"makes it easy to install and update free libraries and tools.\r\n        <a");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=245140\"");

WriteLiteral(">Learn more…</a>\r\n    </li>\r\n\r\n    <li");

WriteLiteral(" class=\"three\"");

WriteLiteral(">\r\n        <h5>Find Web Hosting</h5>\r\n        You can easily find a web hosting c" +
"ompany that offers the right mix of features and price for your applications.\r\n " +
"       <a");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=245143\"");

WriteLiteral(">Learn more…</a>\r\n    </li>\r\n</ol>");

        }
    }
}
