#pragma checksum "I:\Company\MensClothe\Admin\Admin.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B74862BB999D240FA09BFA2AD17D347E80CE1D95"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Admin_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Admin_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "I:\Company\MensClothe\Admin\Admin.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Admin Page";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("featured", () => {

WriteLiteral("\r\n    <section");

WriteLiteral(" class=\"featured\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n            <hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n                <h1>");

            
            #line 9 "I:\Company\MensClothe\Admin\Admin.cshtml"
               Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n                <h2>Men\'s Online Store</h2>\r\n            </hgroup>\r\n\r\n   " +
"     </div>\r\n\r\n\r\n    </section>\r\n");

});

WriteLiteral("<section");

WriteLiteral(" class=\"admin\"");

WriteLiteral(">\r\n\r\n    <nav");

WriteLiteral(" class=\"red\"");

WriteLiteral(">\r\n\r\n");

            
            #line 22 "I:\Company\MensClothe\Admin\Admin.cshtml"
        
            
            #line default
            #line hidden
            
            #line 22 "I:\Company\MensClothe\Admin\Admin.cshtml"
         if (WebSecurity.IsAuthenticated)
        {

            
            #line default
            #line hidden
WriteLiteral("            <ul");

WriteLiteral(" class=\"clear\"");

WriteLiteral(">\r\n                <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Products</a>\r\n                    <ul>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 593), Tuple.Create("\"", 625)
, Tuple.Create(Tuple.Create("", 600), Tuple.Create<System.Object, System.Int32>(Href("~/Products/ProductResults")
, 600), false)
);

WriteLiteral(">View</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 672), Tuple.Create("\"", 706)
, Tuple.Create(Tuple.Create("", 679), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Products/AddProduct")
, 679), false)
);

WriteLiteral(">Add</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 752), Tuple.Create("\"", 786)
, Tuple.Create(Tuple.Create("", 759), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Products/RemoveItem")
, 759), false)
);

WriteLiteral(">Remove</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 835), Tuple.Create("\"", 872)
, Tuple.Create(Tuple.Create("", 842), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Products/ModifyProduct")
, 842), false)
);

WriteLiteral(">Change</a></li>\r\n                    </ul>\r\n                </li>\r\n\r\n           " +
"     <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Category</a>\r\n                    <ul>\r\n                        <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">View</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1100), Tuple.Create("\"", 1135)
, Tuple.Create(Tuple.Create("", 1107), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Category/AddCategory")
, 1107), false)
);

WriteLiteral(">Add</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1181), Tuple.Create("\"", 1219)
, Tuple.Create(Tuple.Create("", 1188), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Category/RemoveCategory")
, 1188), false)
);

WriteLiteral(">Remove</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1268), Tuple.Create("\"", 1306)
, Tuple.Create(Tuple.Create("", 1275), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Category/ModifyCategory")
, 1275), false)
);

WriteLiteral(">Change</a></li>\r\n                    </ul>\r\n                </li>\r\n             " +
"   <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Oroder</a>\r\n                    <ul>\r\n                        <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">View</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1530), Tuple.Create("\"", 1561)
, Tuple.Create(Tuple.Create("", 1537), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Orders/AddOrders")
, 1537), false)
);

WriteLiteral(">Add</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1607), Tuple.Create("\"", 1641)
, Tuple.Create(Tuple.Create("", 1614), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Orders/RemoveOrders")
, 1614), false)
);

WriteLiteral(">Remove</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1690), Tuple.Create("\"", 1724)
, Tuple.Create(Tuple.Create("", 1697), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Orders/ModifyOrders")
, 1697), false)
);

WriteLiteral(">Change</a></li>\r\n                    </ul>\r\n\r\n\r\n                </li>\r\n         " +
"       <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Customer</a>\r\n                    <ul>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1899), Tuple.Create("\"", 1936)
, Tuple.Create(Tuple.Create("", 1906), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Customer/ViewCustomers")
, 1906), false)
);

WriteLiteral(">View</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1983), Tuple.Create("\"", 2018)
, Tuple.Create(Tuple.Create("", 1990), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Customer/AddCustomer")
, 1990), false)
);

WriteLiteral(">Add</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2064), Tuple.Create("\"", 2102)
, Tuple.Create(Tuple.Create("", 2071), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Customer/RemoveCustomer")
, 2071), false)
);

WriteLiteral(">Remove</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2151), Tuple.Create("\"", 2189)
, Tuple.Create(Tuple.Create("", 2158), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Customer/ModifyCustomer")
, 2158), false)
);

WriteLiteral(">Change</a></li>\r\n                    </ul>\r\n                </li>\r\n             " +
"   <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Supplier</a>\r\n                    <ul>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2360), Tuple.Create("\"", 2396)
, Tuple.Create(Tuple.Create("", 2367), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Supplier/ViewSupplier")
, 2367), false)
);

WriteLiteral(">View</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2443), Tuple.Create("\"", 2478)
, Tuple.Create(Tuple.Create("", 2450), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Supplier/AddSupplier")
, 2450), false)
);

WriteLiteral(">Add</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2524), Tuple.Create("\"", 2563)
, Tuple.Create(Tuple.Create("", 2531), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Supplier/RemoveSupplierr")
, 2531), false)
);

WriteLiteral(">Remove</a></li>\r\n                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2612), Tuple.Create("\"", 2650)
, Tuple.Create(Tuple.Create("", 2619), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Supplier/ModifySupplier")
, 2619), false)
);

WriteLiteral(">Change</a></li>\r\n                    </ul>\r\n                </li>\r\n            <" +
"/ul>\r\n");

            
            #line 69 "I:\Company\MensClothe\Admin\Admin.cshtml"
        }
        else
        {
            var returnUrl = "~/Account/Login?ReturnUrl=" + Request.Url.LocalPath;
            Response.Redirect(returnUrl);

        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </nav>\r\n\r\n\r\n</section>\r\n\r\n\r\n");

        }
    }
}
