#pragma checksum "I:\Company\MensClothe\Admin\Category\RemoveCategory.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B0B208DBACA2AE01831EA3F558555573C87AB2FD"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Category_RemoveCategory_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Category_RemoveCategory_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "I:\Company\MensClothe\Admin\Category\RemoveCategory.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Clothes";
    dynamic CatRecord = null;
    var catID = "";
    var CategoryName = "";
    var Description = "";
    var items = new List<SelectListItem>();
    var i = 0;

    if (IsPost)
    {
        var detailForm = Request.Form["detailform"];
        var delDetail = Request.Form["deleteDetail"];
        var delConfirm = Request.Form["deleteConfirm"];


        if (!string.IsNullOrEmpty(Request.Form["DDLid"]))
        {
            Session.Add("categoryID", Request.Form["DDLid"]);
        }

        if (delDetail != null && Session["categoryID"] != null)
        {
            catID = Session["categoryID"].ToString();


            CatRecord = DAL.Category.getCategoryDetail(int.Parse(catID));
            if (CatRecord != null)
            {

                CategoryName = Convert.ToString(CatRecord["categoryname"]);
                Description = Convert.ToString(CatRecord["description"]);
            }
        }
        else if (delConfirm != null && Session["categoryID"] != null)
        {
            catID = Session["categoryID"].ToString();

            i = DAL.Category.DeleteCategory(catID);


        }


    }
    // Check if user already exists
    var user = DAL.Category.getProductRecodCollections();

    if (user != null)
    {

        items.Add(new SelectListItem { Text = "Select....", Value = "" });
        foreach (var item in user)
        {

            items.Add(new SelectListItem { Text = item.categoryname, Value = Convert.ToString(item.categoryid) });

        }

    }
            
               
            
        
    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 76 "I:\Company\MensClothe\Admin\Category\RemoveCategory.cshtml"
   Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Delete Category</h2>\r\n</hgroup>\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 81 "I:\Company\MensClothe\Admin\Category\RemoveCategory.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 83 "I:\Company\MensClothe\Admin\Category\RemoveCategory.cshtml"
Write(Html.ValidationSummary("Adding Products was unsuccessful. Please correct the errors and try again.", excludeFieldErrors: true, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <fieldset>\r\n        <legend>Registration Form</legend>\r\n        <ol>\r\n\r\n " +
"           <li");

WriteLiteral(" class=\"Clothes\"");

WriteLiteral(">\r\n                <label>\r\n                    Select Products Item to be Delete" +
"d:\r\n                </label>\r\n");

WriteLiteral("                ");

            
            #line 93 "I:\Company\MensClothe\Admin\Category\RemoveCategory.cshtml"
           Write(Html.DropDownList("DDLid", items));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n\r\n            </li>\r\n\r\n        </ol>\r\n\r\n        <div");

WriteLiteral(" id=\"detailform\"");

WriteLiteral("   ");

            
            #line 102 "I:\Company\MensClothe\Admin\Category\RemoveCategory.cshtml"
                                if (CatRecord == null)
                               {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 103 "I:\Company\MensClothe\Admin\Category\RemoveCategory.cshtml"
                                                                  }
            
            #line default
            #line hidden
WriteLiteral("\">\r\n\r\n            <ol>\r\n\r\n                <li class=\"Price\">\r\n                   " +
" <label>\r\n                        Category  Name</label>\r\n                    <i" +
"nput type=\"text\"  id=\"Price\" name=\"Price\" value=\"");

            
            #line 110 "I:\Company\MensClothe\Admin\Category\RemoveCategory.cshtml"
                                                                  Write(CategoryName);

            
            #line default
            #line hidden
WriteLiteral("\" ) />\r\n                    ");

WriteLiteral("\r\n\r\n                </li>\r\n\r\n                <li class=\"description\">\r\n          " +
"          <label>\r\n                        Description</label>\r\n                " +
"    <input type=\"text\" id=\"Desc\" name=\"Description\"  value=\"");

            
            #line 118 "I:\Company\MensClothe\Admin\Category\RemoveCategory.cshtml"
                                                                       Write(Description);

            
            #line default
            #line hidden
WriteLiteral(@""" />
                </li>
                <li class=""recaptcha""></li>
            </ol>
            <input type=""submit"" id=""deleteConfirm"" name=""deleteConfirm"" value=""Confirm"" />
        </div>
    </fieldset>
    <p>
        <input type=""submit"" id=""deleteDetail""  name=""deleteDetail"" value=""Delete Category""  ");

            
            #line 126 "I:\Company\MensClothe\Admin\Category\RemoveCategory.cshtml"
                                                                                              if (CatRecord != null)
                                                                                                  {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 127 "I:\Company\MensClothe\Admin\Category\RemoveCategory.cshtml"
                                                                                                                                     }
            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    </p>\r\n    <ul>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3779), Tuple.Create("\"", 3788)
, Tuple.Create(Tuple.Create("", 3786), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 3786), false)
);

WriteLiteral(">Home</a></li>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3819), Tuple.Create("\"", 3839)
, Tuple.Create(Tuple.Create("", 3826), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Admin")
, 3826), false)
);

WriteLiteral(">Admin</a></li>\r\n\r\n    </ul>\r\n</form>\r\n");

        }
    }
}
