#pragma checksum "I:\Company\MensClothe\Account\Login.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "F052BF6142931FE2429C4F999D4B33851468D622"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Account_Login_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Account_Login_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "I:\Company\MensClothe\Account\Login.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Log in";

    // Initialize general page variables
    var email = "";
    var password = "";
    var rememberMe = false;

    var returnUrl = Request.QueryString["ReturnUrl"];
    if (returnUrl.IsEmpty())
    {
        // Some external login providers always require a return URL value
        returnUrl = Href("~/");
    }

    // Setup validation
    Validation.RequireField("email", "You must specify an email address.");
    Validation.RequireField("password", "You must specify a password.");
    Validation.Add("password",
        Validator.StringLength(
            maxLength: Int32.MaxValue,
            minLength: 6,
            errorMessage: "Password must be at least 6 characters"));

    // If this is a POST request, validate and process data
    if (IsPost)
    {
        AntiForgery.Validate();
        // is this an external login request?
        string provider = Request.Form["provider"];
        if (!provider.IsEmpty())
        {
            OAuthWebSecurity.RequestAuthentication(provider, Href("~/Account/RegisterService", new { returnUrl }));
            return;
        }
        else if (Validation.IsValid())
        {
            email = Request.Form["email"];
            password = Request.Form["password"];
            rememberMe = Request.Form["rememberMe"].AsBool();

            if (WebSecurity.UserExists(email) && WebSecurity.GetPasswordFailuresSinceLastSuccess(email) > 4 && WebSecurity.GetLastPasswordFailureDate(email).AddSeconds(60) > DateTime.UtcNow)
            {
                Response.Redirect("~/Account/AccountLockedOut");
                return;
            }

            // Attempt to log in using provided credentials
            if (WebSecurity.Login(email, password, rememberMe))
            {
                Context.RedirectLocal(returnUrl);
                return;
            }
            else
            {
                ModelState.AddFormError("The user name or password provided is incorrect.");
            }
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 70 "I:\Company\MensClothe\Account\Login.cshtml"
   Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n</hgroup>\r\n\r\n<section");

WriteLiteral(" id=\"loginForm\"");

WriteLiteral(">\r\n    <h2>Use a local account to log in.</h2>\r\n    <form");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 76 "I:\Company\MensClothe\Account\Login.cshtml"
   Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");

WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 78 "I:\Company\MensClothe\Account\Login.cshtml"
   Write(Html.ValidationSummary("Log in was unsuccessful. Please correct the errors and try again.", excludeFieldErrors: true, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <fieldset>\r\n            <legend>Log in to Your Account</legend>\r\n    " +
"        <ol>\r\n                <li");

WriteLiteral(" class=\"email\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"email\"");

WriteLiteral(" ");

            
            #line 84 "I:\Company\MensClothe\Account\Login.cshtml"
                                        if (!ModelState.IsValidField("email"))
                                       {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 85 "I:\Company\MensClothe\Account\Login.cshtml"
                                                                        }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                        Email address</label>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"email\"");

WriteLiteral(" name=\"email\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3135), Tuple.Create("\"", 3149)
            
            #line 87 "I:\Company\MensClothe\Account\Login.cshtml"
, Tuple.Create(Tuple.Create("", 3143), Tuple.Create<System.Object, System.Int32>(email
            
            #line default
            #line hidden
, 3143), false)
);

WriteLiteral(" ");

            
            #line 87 "I:\Company\MensClothe\Account\Login.cshtml"
                                                                         Write(Validation.For("email"));

            
            #line default
            #line hidden
WriteLiteral("/>\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 89 "I:\Company\MensClothe\Account\Login.cshtml"
               Write(Html.ValidationMessage("email"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li");

WriteLiteral(" class=\"password\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"password\"");

WriteLiteral(" ");

            
            #line 92 "I:\Company\MensClothe\Account\Login.cshtml"
                                           if (!ModelState.IsValidField("password"))
                                          {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 93 "I:\Company\MensClothe\Account\Login.cshtml"
                                                                           }
            
            #line default
            #line hidden
WriteLiteral(">Password</label>\r\n                    <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"password\"");

WriteLiteral(" name=\"password\"");

WriteLiteral(" ");

            
            #line 94 "I:\Company\MensClothe\Account\Login.cshtml"
                                                                    Write(Validation.For("password"));

            
            #line default
            #line hidden
WriteLiteral("/>\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 96 "I:\Company\MensClothe\Account\Login.cshtml"
               Write(Html.ValidationMessage("password"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li");

WriteLiteral(" class=\"remember-me\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"rememberMe\"");

WriteLiteral(" name=\"rememberMe\"");

WriteLiteral(" value=\"true\"");

WriteAttribute("checked", Tuple.Create(" checked=\"", 3944), Tuple.Create("\"", 3965)
            
            #line 99 "I:\Company\MensClothe\Account\Login.cshtml"
                   , Tuple.Create(Tuple.Create("", 3954), Tuple.Create<System.Object, System.Int32>(rememberMe
            
            #line default
            #line hidden
, 3954), false)
);

WriteLiteral(" />\r\n                    <label");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(" for=\"rememberMe\"");

WriteLiteral(">Remember me?</label>\r\n                </li>\r\n            </ol>\r\n            <inp" +
"ut");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Log in\"");

WriteLiteral(" />\r\n        </fieldset>\r\n    </form>\r\n    <p>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4201), Tuple.Create("\"", 4226)
, Tuple.Create(Tuple.Create("", 4208), Tuple.Create<System.Object, System.Int32>(Href("~/Account/Register")
, 4208), false)
);

WriteLiteral(">Don\'t have a Account?</a>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4265), Tuple.Create("\"", 4296)
, Tuple.Create(Tuple.Create("", 4272), Tuple.Create<System.Object, System.Int32>(Href("~/Account/ForgotPassword")
, 4272), false)
);

WriteLiteral(">Did you forget your password?</a>\r\n    </p>\r\n</section>\r\n\r\n<section");

WriteLiteral(" class=\"social\"");

WriteLiteral(" id=\"socialLoginForm\"");

WriteLiteral(">\r\n    <h2>Use another service to log in.</h2>\r\n");

WriteLiteral("    ");

            
            #line 114 "I:\Company\MensClothe\Account\Login.cshtml"
Write(RenderPage("~/Account/_ExternalLoginsList.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</section>\r\n");

        }
    }
}
