#pragma checksum "I:\Company\MensClothe\Products\ProductResults.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8357AD17943FE94728E6C4118F7EB521F8584671"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Products_ProductResults_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        #line 71 "I:\Company\MensClothe\Products\ProductResults.cshtml"
 
    public void SelectedItemClick(string _id)
    {
        var ProductRecord = Products.getProductDetail(int.Parse(_id));
    }

        #line default
        #line hidden
        
        
        public _Page_Products_ProductResults_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 86), Tuple.Create("\"", 124)
, Tuple.Create(Tuple.Create("", 92), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 92), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 148), Tuple.Create("\"", 198)
, Tuple.Create(Tuple.Create("", 154), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 154), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n        $(document).ready(function () {\r\n\r\n        });\r\n\r\n        function S" +
"electedItemClick(obj) {\r\n            debugger;\r\n            popupwin = window.op" +
"en(\'");

            
            #line 14 "I:\Company\MensClothe\Products\ProductResults.cshtml"
                               Write(MensClothe.AspControlUtil.getAppPath());

            
            #line default
            #line hidden
WriteLiteral(@"Products/DetailProductResult' + ""?resultIndex="" + obj.id + ""&isPopup=1"", 'Detail', 'height=' + 600 + ',width=' + 520 + ',scrollbars=yes,left=400,top=300');
            popupwin.focus();
        }

        function Add2CartClick(obj) {

            debugger;

            id = obj.id.split('_')[0];
            $.ajax({
                type: ""POST"",
                url: """);

            
            #line 25 "I:\Company\MensClothe\Products\ProductResults.cshtml"
                 Write(MensClothe.AspControlUtil.getAppPath());

            
            #line default
            #line hidden
WriteLiteral(@"Web_Service/WebService.asmx/SelectedItemClick"",
                contentType: ""application/json; charset=utf-8"",
                data: ""{_id:'"" + id + ""'}"",
                dataType: ""json"",
                success: OnSucceess,
                error: OnError
            });
        }



        function OnSucceess() {

        }
        function OnError() {


        }




    </script>

");

});

WriteLiteral("\r\n");

            
            #line 51 "I:\Company\MensClothe\Products\ProductResults.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Clothes";
    List<Products> ProductRecords = new List<Products>();

    if (Request.QueryString["cat"] != null)
    {
        int catid = int.Parse(Request.QueryString["cat"].ToString());

        ProductRecords = Products.getCategoryWiseProducts(catid);
    }
    else
    {
        ProductRecords = Products.getProductRecodCollections();
    }
    
   

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("    ");

            
            #line 81 "I:\Company\MensClothe\Products\ProductResults.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n\r\n    <fieldset>\r\n        <legend>Products Results </legend>\r\n        <div");

WriteLiteral(" id=\"detailform\"");

WriteLiteral("   ");

            
            #line 86 "I:\Company\MensClothe\Products\ProductResults.cshtml"
                                if (ProductRecords == null)
                               {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 87 "I:\Company\MensClothe\Products\ProductResults.cshtml"
                                                                  }
            
            #line default
            #line hidden
WriteLiteral(@""">
            <table>
                <tr>
                    <td>
                        <label>
                            <b>Price</b></label>
                    </td>

                    <td>
                        <label for=""ItemImage"">
                            <b>Quantity</b>
                        </label>

                    </td>

                    <td>
                        <label for=""ItemImage"">
                            <b>Image</b>
                        </label>
                    </td>

                    <td>
                        <label>
                            <b>Size</b></label>
                    </td>
                    <td>
                        <label>
                            <b>Description</b></label>
                    </td>

                </tr>
");

            
            #line 118 "I:\Company\MensClothe\Products\ProductResults.cshtml"
                
            
            #line default
            #line hidden
            
            #line 118 "I:\Company\MensClothe\Products\ProductResults.cshtml"
                 foreach (var item in ProductRecords)
                { 

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>\r\n                         " +
"   <label");

WriteLiteral(" id=\"Price\"");

WriteLiteral(">");

            
            #line 122 "I:\Company\MensClothe\Products\ProductResults.cshtml"
                                         Write(item.unitprice);

            
            #line default
            #line hidden
WriteLiteral(" </label>\r\n                        </td>\r\n                        <td>\r\n\r\n       " +
"                     <label");

WriteLiteral(" id=\"quantity\"");

WriteLiteral(">");

            
            #line 126 "I:\Company\MensClothe\Products\ProductResults.cshtml"
                                            Write(item.quantity);

            
            #line default
            #line hidden
WriteLiteral(" </label>\r\n                        </td>\r\n                        <td>\r\n         " +
"                   <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3475), Tuple.Create("\"", 3552)
            
            #line 129 "I:\Company\MensClothe\Products\ProductResults.cshtml"
, Tuple.Create(Tuple.Create("", 3481), Tuple.Create<System.Object, System.Int32>(MensClothe.AspControlUtil.getFullImagePath(Convert.ToString(item.img))
            
            #line default
            #line hidden
, 3481), false)
);

WriteLiteral(" alt=\"Red dot\"");

WriteLiteral(" width=\"100\"");

WriteLiteral(" height=\"150\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                  " +
"          <label");

WriteLiteral(" id=\"size\"");

WriteLiteral(">");

            
            #line 133 "I:\Company\MensClothe\Products\ProductResults.cshtml"
                                        Write(item.categoryID);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        </td>\r\n                        <td>\r\n          " +
"                  <label");

WriteLiteral(" id=\"Desc\"");

WriteLiteral(">");

            
            #line 136 "I:\Company\MensClothe\Products\ProductResults.cshtml"
                                        Write(item.Description);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        </td>\r\n\r\n                        <td>\r\n        " +
"                    <input");

WriteAttribute("id", Tuple.Create(" id=\"", 4097), Tuple.Create("\"", 4114)
            
            #line 140 "I:\Company\MensClothe\Products\ProductResults.cshtml"
, Tuple.Create(Tuple.Create("", 4102), Tuple.Create<System.Object, System.Int32>(item.ItemID
            
            #line default
            #line hidden
, 4102), false)
);

WriteLiteral(" type=\"button\"");

WriteAttribute("name", Tuple.Create(" name=\"", 4129), Tuple.Create("\"", 4148)
            
            #line 140 "I:\Company\MensClothe\Products\ProductResults.cshtml"
, Tuple.Create(Tuple.Create("", 4136), Tuple.Create<System.Object, System.Int32>(item.ItemID
            
            #line default
            #line hidden
, 4136), false)
);

WriteLiteral("  \r\nonclick=\"SelectedItemClick(this);\"");

WriteLiteral("  value=\"View Detail Item\"");

WriteLiteral("  />\r\n                        </td>\r\n                        <td>\r\n              " +
"              <input");

WriteAttribute("id", Tuple.Create(" id=\"", 4314), Tuple.Create("\"", 4356)
            
            #line 144 "I:\Company\MensClothe\Products\ProductResults.cshtml"
, Tuple.Create(Tuple.Create("", 4319), Tuple.Create<System.Object, System.Int32>(string.Concat(item.ItemID, "_index")
            
            #line default
            #line hidden
, 4319), false)
);

WriteLiteral(" onclick=\"Add2CartClick(this);\"");

WriteLiteral(" type=\"submit\"");

WriteAttribute("name", Tuple.Create(" name=\"", 4402), Tuple.Create("\"", 4421)
            
            #line 144 "I:\Company\MensClothe\Products\ProductResults.cshtml"
                                                 , Tuple.Create(Tuple.Create("", 4409), Tuple.Create<System.Object, System.Int32>(item.ItemID
            
            #line default
            #line hidden
, 4409), false)
);

WriteLiteral(" value=\"Add to Cart\"");

WriteLiteral("  />\r\n                        </td>\r\n\r\n                    </tr>\r\n");

            
            #line 148 "I:\Company\MensClothe\Products\ProductResults.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </table>\r\n        </div>\r\n    </fieldset>\r\n    <ul>\r\n        <li><a h" +
"ref=\"~/\">Home</a></li>\r\n        <li><a href=\"~/Admin/Admin\">Admin</a></li>\r\n    " +
"</ul>\r\n</form>\r\n");

        }
    }
}
