#pragma checksum "I:\Company\MensClothe\Account\_ExternalLoginsList.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "D9968688CD012FD67B4399DB35F270D8599A6B18"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Account__ExternalLoginsList_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Account__ExternalLoginsList_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "I:\Company\MensClothe\Account\_ExternalLoginsList.cshtml"
 if (OAuthWebSecurity.RegisteredClientData.Count == 0) {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"message-info\"");

WriteLiteral(">\r\n        <p>\r\n            There are no external authentication services configu" +
"red. See <a");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=226949\"");

WriteLiteral(">this article</a>\r\n            for details on setting up this ASP.NET application" +
" to support logging in via external services.\r\n        </p>\r\n    </div>\r\n");

            
            #line 8 "I:\Company\MensClothe\Account\_ExternalLoginsList.cshtml"
} else {

            
            #line default
            #line hidden
WriteLiteral("    <form");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 10 "I:\Company\MensClothe\Account\_ExternalLoginsList.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    <fieldset");

WriteLiteral(" id=\"socialLoginList\"");

WriteLiteral(">\r\n        <legend>Log in using another service</legend>\r\n        <p>\r\n");

            
            #line 14 "I:\Company\MensClothe\Account\_ExternalLoginsList.cshtml"
            
            
            #line default
            #line hidden
            
            #line 14 "I:\Company\MensClothe\Account\_ExternalLoginsList.cshtml"
             foreach (var client in OAuthWebSecurity.RegisteredClientData) {

            
            #line default
            #line hidden
WriteLiteral("                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" name=\"provider\"");

WriteAttribute("value", Tuple.Create(" value=\"", 686), Tuple.Create("\"", 735)
            
            #line 15 "I:\Company\MensClothe\Account\_ExternalLoginsList.cshtml"
, Tuple.Create(Tuple.Create("", 694), Tuple.Create<System.Object, System.Int32>(client.AuthenticationClient.ProviderName
            
            #line default
            #line hidden
, 694), false)
);

WriteAttribute("title", Tuple.Create("\r\n                        title=\"", 736), Tuple.Create("\"", 814)
, Tuple.Create(Tuple.Create("", 769), Tuple.Create("Log", 769), true)
, Tuple.Create(Tuple.Create(" ", 772), Tuple.Create("in", 773), true)
, Tuple.Create(Tuple.Create(" ", 775), Tuple.Create("using", 776), true)
, Tuple.Create(Tuple.Create(" ", 781), Tuple.Create("your", 782), true)
            
            #line 16 "I:\Company\MensClothe\Account\_ExternalLoginsList.cshtml"
, Tuple.Create(Tuple.Create(" ", 786), Tuple.Create<System.Object, System.Int32>(client.DisplayName
            
            #line default
            #line hidden
, 787), false)
, Tuple.Create(Tuple.Create(" ", 806), Tuple.Create("account", 807), true)
);

WriteLiteral(">");

            
            #line 16 "I:\Company\MensClothe\Account\_ExternalLoginsList.cshtml"
                                                                         Write(client.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 17 "I:\Company\MensClothe\Account\_ExternalLoginsList.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </p>\r\n    </fieldset>\r\n    </form>\r\n");

            
            #line 21 "I:\Company\MensClothe\Account\_ExternalLoginsList.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
