#pragma checksum "I:\Company\MensClothe\Admin\Category\ModifyCategory.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "924A11160019D20A87B637E0A7BAF29FA18EF6BE"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Category_ModifyCategory_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Category_ModifyCategory_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "I:\Company\MensClothe\Admin\Category\ModifyCategory.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Clothes";
    dynamic CatRecord = null;
    var Description = "";
    var CategoryName = "";
    var categoryid = 0;
    var items = new List<SelectListItem>();
    var i = 0;

    Validation.RequireField("CategoryName", "You must specify the  Category name.");
   

    if (IsPost)
    {
        var detailForm = Request.Form["detailform"];
        var updateDetail = Request.Form["UpdateDetail"];
        var updateConfirm = Request.Form["UpdateConfirm"];


        if (!string.IsNullOrEmpty(Request.Form["DDLid"]))
        {
            Session.Add("catId", Request.Form["DDLid"]);
        }

        if (updateDetail != null && Session["catId"] != null)
        {
            categoryid = int.Parse(Session["catId"].ToString());
   
            CatRecord = DAL.Category.getCategoryDetail(categoryid);
            if (CatRecord != null)
            {

                Description = Convert.ToString(CatRecord["Description"]);
                CategoryName = CatRecord["categoryname"];
            }
        }
        else if (updateConfirm != null && Session["catId"] != null)
        {

            Description = Request.Form["Description"];
            CategoryName = Request.Form["categoryname"];

            categoryid = int.Parse(Session["catId"].ToString());
            // db = Database.Open("mensClothe");
            i = DAL.Category.UpdateCategory(CategoryName, Description, categoryid);
            if (i == 0)
            {
                string url = "~/ErrorPage?ErrorMessage=" + "Dabse Error Occured";
                Response.Redirect(url);
            }


        }


    }

    
    List<DAL.Category> CategoryRecords = DAL.Category.getProductRecodCollections();
    if (CategoryRecords != null)
    {

        items.Add(new SelectListItem { Text = "Select....", Value = "" });
        foreach (var item in CategoryRecords)
        {

            items.Add(new SelectListItem { Text = item.categoryname, Value = Convert.ToString(item.categoryid) });

        }

    }
    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 83 "I:\Company\MensClothe\Admin\Category\ModifyCategory.cshtml"
   Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Delete Products Item</h2>\r\n</hgroup>\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 88 "I:\Company\MensClothe\Admin\Category\ModifyCategory.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 90 "I:\Company\MensClothe\Admin\Category\ModifyCategory.cshtml"
Write(Html.ValidationSummary("Adding Products was unsuccessful. Please correct the errors and try again.", excludeFieldErrors: true, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <fieldset>\r\n        <legend>Update Category</legend>\r\n        <ol>\r\n\r\n   " +
"         <li");

WriteLiteral(" class=\"Category\"");

WriteLiteral(">\r\n                <label>\r\n                    Select the Category to modify:\r\n " +
"               </label>\r\n");

WriteLiteral("                ");

            
            #line 100 "I:\Company\MensClothe\Admin\Category\ModifyCategory.cshtml"
           Write(Html.DropDownList("DDLid", items));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n\r\n        </ol>\r\n\r\n        <div");

WriteLiteral(" id=\"detailform\"");

WriteLiteral("   ");

            
            #line 105 "I:\Company\MensClothe\Admin\Category\ModifyCategory.cshtml"
                                if (CatRecord == null )
                               {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 106 "I:\Company\MensClothe\Admin\Category\ModifyCategory.cshtml"
                                                                  }
            
            #line default
            #line hidden
WriteLiteral("\">\r\n\r\n            <ol>\r\n\r\n                <li class=\"Price\">\r\n                   " +
" <label>\r\n                        Cateogory Name</label>\r\n                    <i" +
"nput type=\"text\" id=\"CategoryName\" name=\"CategoryName\" value=\"");

            
            #line 113 "I:\Company\MensClothe\Admin\Category\ModifyCategory.cshtml"
                                                                               Write(CategoryName);

            
            #line default
            #line hidden
WriteLiteral("\" ) />\r\n                    ");

WriteLiteral("\r\n\r\n                </li>\r\n\r\n\r\n                <li class=\"description\">\r\n        " +
"            <label>\r\n                        Description</label>\r\n              " +
"      <input type=\"text\" id=\"Desc\" name=\"Description\"  value=\"");

            
            #line 122 "I:\Company\MensClothe\Admin\Category\ModifyCategory.cshtml"
                                                                       Write(Description);

            
            #line default
            #line hidden
WriteLiteral(@""" />
                </li>
                <li class=""recaptcha""></li>
            </ol>
            <input type=""submit"" id=""UpdateConfirm"" name=""UpdateConfirm"" value=""Confirm"" />
        </div>
    </fieldset>
    <p>
        <input type=""submit"" id=""UpdateDetail""  name=""UpdateDetail"" value=""Update Products Item""  ");

            
            #line 130 "I:\Company\MensClothe\Admin\Category\ModifyCategory.cshtml"
                                                                                                   if (CatRecord != null)
                                                                                                  {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 131 "I:\Company\MensClothe\Admin\Category\ModifyCategory.cshtml"
                                                                                                                                     }
            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    </p>\r\n    <ul>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4253), Tuple.Create("\"", 4262)
, Tuple.Create(Tuple.Create("", 4260), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 4260), false)
);

WriteLiteral(">Home</a></li>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4293), Tuple.Create("\"", 4313)
, Tuple.Create(Tuple.Create("", 4300), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/Admin")
, 4300), false)
);

WriteLiteral(">Admin</a></li>\r\n\r\n    </ul>\r\n</form>\r\n");

        }
    }
}
