#pragma checksum "I:\Company\MensClothe\App_Code\MensStore.cs" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5146D60A2FEFF35DDC914AB739CDDA3502AF4999"

#line 1 "I:\Company\MensClothe\App_Code\MensStore.cs"
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


#line default
#line hidden
