#pragma checksum "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3C40750C47EF4F9B60104D1591B0FBFC26D78900"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Category_AddCategory_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Category_AddCategory_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Category";

    // Initialize general page variables
    var CategoryName = "";
    var Description = "";
   


    // Setup validation
    Validation.RequireField("CategoryName", "You must specify the  Category name.");
    Validation.RequireField("Description", "Description cannot be blank.");
   


    if (IsPost)
    {
        AntiForgery.Validate();




        CategoryName = Request.Form["CategoryName"];
        Description = Request.Form["Description"];
               
        if (Validation.IsValid())
        {


            int result = DAL.Category.insertCategory(CategoryName, Description);
            if (result == 0)
            {
                string url = "~/ErrorPage?ErrorMessage=" + "Dabse Error Occured";
                Response.Redirect(url);
            }

            
            
            
            
            
            
            

        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 57 "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml"
   Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Add a new Category</h2>\r\n</hgroup>\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 62 "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 64 "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml"
Write(Html.ValidationSummary("Adding new Category was unsuccessful. Please correct the errors and try again.", excludeFieldErrors: true, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <fieldset>\r\n        <legend>Registration Form</legend>\r\n        <ol>\r\n\r\n " +
"           <li");

WriteLiteral(" class=\"Category\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"CategoryName\"");

WriteLiteral(" ");

            
            #line 71 "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml"
                                           if (!ModelState.IsValidField("CategoryName"))
                                     {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 72 "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml"
                                                                      }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                    Category Name\r\n                </label>\r\n                <" +
"input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CatName\"");

WriteLiteral(" name=\"CategoryName\"");

WriteLiteral("  ");

            
            #line 75 "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml"
                                                                Write(Validation.For("CategoryName"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 77 "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml"
           Write(Html.ValidationMessage("CategoryName"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n\r\n            <li");

WriteLiteral(" class=\"description\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"ItemImage\"");

WriteLiteral(" ");

            
            #line 81 "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml"
                                        if (!ModelState.IsValidField("Description"))
                                       {
            
            #line default
            #line hidden
WriteLiteral("class=\"error-label\"");

            
            #line 82 "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml"
                                                                        }
            
            #line default
            #line hidden
WriteLiteral(">Enter the Description</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Desc\"");

WriteLiteral(" name=\"Description\"");

WriteLiteral(" ");

            
            #line 83 "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml"
                                                           Write(Validation.For("Description"));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 85 "I:\Company\MensClothe\Admin\Category\AddCategory.cshtml"
           Write(Html.ValidationMessage("Description"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n\r\n            \r\n            <li");

WriteLiteral(" class=\"recaptcha\"");

WriteLiteral("></li>\r\n        </ol>\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Add Category\"");

WriteLiteral(" />\r\n    </fieldset>\r\n</form>\r\n");

        }
    }
}
