#pragma checksum "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9E18148D494A2EFA3C0839970444D19E993FEA21"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    using Microsoft.Web.WebPages.OAuth;
    using DotNetOpenAuth.AspNet;
    
    
    public class _Page_Admin_Supplier_RemoveSupplier_cshtml : System.Web.WebPages.WebPage {
        
#line hidden
        
        public _Page_Admin_Supplier_RemoveSupplier_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 84), Tuple.Create("\"", 122)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 90), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 146), Tuple.Create("\"", 196)
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.unobtrusive.min.js")
, 152), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

            
            #line 7 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
  
    Layout = "~/_SiteLayout.cshtml";
    Page.Title = "Clothes";
    dynamic SuppliersRecord = new DAL.Suppliers();
    var suppId = 0;
    var items = new List<SelectListItem>();
    var i = 0;


    if (IsPost)
    {
        var detailForm = Request.Form["detailform"];
        var delDetail = Request.Form["deleteDetail"];
        var delConfirm = Request.Form["deleteConfirm"];


        if (!string.IsNullOrEmpty(Request.Form["DDLid"]))
        {
            Session.Add("suppId", Request.Form["DDLid"]);
        }

        if (delDetail != null && Session["suppId"] != null)
        {
            suppId = int.Parse(Session["suppId"].ToString());
            SuppliersRecord = DAL.Suppliers.getSuppliersDetail(suppId);

        }
        else if (delConfirm != null && Session["suppId"] != null)
        {
            suppId = int.Parse(Session["suppId"].ToString());

            i = DAL.Suppliers.DeleteSuppliers(suppId.ToString());


        }


    }
    var suppliers = DAL.Suppliers.getAllSuppliers();
    if (suppliers != null)
    {
        items.Add(new SelectListItem { Text = "Select....", Value = "" });
        foreach (var item in suppliers)
        {
            items.Add(new SelectListItem { Text = item.companyname, Value = Convert.ToString(item.supplierid) });
        }

    }
 

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 59 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
   Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>Delete Supplier</h2>\r\n</hgroup>\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 64 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
Write(AntiForgery.GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 66 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
Write(Html.ValidationSummary("Adding Products was unsuccessful. Please correct the errors and try again.", excludeFieldErrors: true, htmlAttributes: null));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <fieldset>\r\n        <legend>Delete Supplier</legend>\r\n        <ol>\r\n     " +
"       <li");

WriteLiteral(" class=\"Clothes\"");

WriteLiteral(">\r\n                <label>\r\n                    Details for the  Supplier to be d" +
"eleted  :\r\n                </label>\r\n");

WriteLiteral("                ");

            
            #line 75 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
           Write(Html.DropDownList("DDLid", items));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n        </ol>\r\n        <div");

WriteLiteral(" id=\"detailform\"");

WriteLiteral("   ");

            
            #line 78 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
                                if (SuppliersRecord.supplierid == 0)
                               {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 79 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
                                                                  }
            
            #line default
            #line hidden
WriteLiteral("   >\r\n            <ol>\r\n                <li>\r\n                    <label");

WriteLiteral(" for=\"txtCompanyName\"");

WriteLiteral(">\r\n                        Company  Name:\r\n                   </label>\r\n         " +
"       </li>\r\n                <li>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtCompanyName\"");

WriteLiteral(" name=\"txtCompanyName\"");

WriteAttribute("value", Tuple.Create("  value=\"", 2679), Tuple.Create("\"", 2716)
            
            #line 87 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
         , Tuple.Create(Tuple.Create("", 2688), Tuple.Create<System.Object, System.Int32>(SuppliersRecord.companyname
            
            #line default
            #line hidden
, 2688), false)
);

WriteLiteral("  />\r\n");

WriteLiteral("                    ");

            
            #line 88 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
               Write(Html.ValidationMessage("txtCompanyName"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ol>\r\n\r\n            <ol>\r\n                <" +
"li>\r\n                    <label");

WriteLiteral(" for=\"txtName\"");

WriteLiteral(">\r\n                        ContactName:\r\n                    </label>\r\n          " +
"      </li>\r\n                <li>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtName\"");

WriteLiteral(" name=\"txtName\"");

WriteAttribute("value", Tuple.Create("  value=\"", 3092), Tuple.Create("\"", 3129)
            
            #line 99 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
, Tuple.Create(Tuple.Create("", 3101), Tuple.Create<System.Object, System.Int32>(SuppliersRecord.contactname
            
            #line default
            #line hidden
, 3101), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                    ");

            
            #line 100 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
               Write(Html.ValidationMessage("txtName"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ol>\r\n            <ol>\r\n                <li" +
">\r\n                    <label");

WriteLiteral(" for=\"txtAddress\"");

WriteLiteral(">\r\n                        Address:\r\n                    </label>\r\n              " +
"  </li>\r\n                <li>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtAddress\"");

WriteLiteral(" name=\"txtAddress\"");

WriteAttribute("value", Tuple.Create("  value=\"", 3500), Tuple.Create("\"", 3533)
            
            #line 110 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
 , Tuple.Create(Tuple.Create("", 3509), Tuple.Create<System.Object, System.Int32>(SuppliersRecord.address
            
            #line default
            #line hidden
, 3509), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                    ");

            
            #line 111 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
               Write(Html.ValidationMessage("txtAddress"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ol>\r\n            <ol>\r\n                <li" +
">\r\n                    <label");

WriteLiteral(" for=\"txtCity\"");

WriteLiteral(">\r\n                        City:\r\n                    </label>\r\n                <" +
"/li>\r\n                <li>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtCity\"");

WriteLiteral(" name=\"txtCity\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3895), Tuple.Create("\"", 3924)
            
            #line 121 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
, Tuple.Create(Tuple.Create("", 3903), Tuple.Create<System.Object, System.Int32>(SuppliersRecord.city
            
            #line default
            #line hidden
, 3903), false)
);

WriteLiteral(" \'");

            
            #line 121 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
                                                                                             Write(Validation.For("txtCity"));

            
            #line default
            #line hidden
WriteLiteral("\' />\r\n");

WriteLiteral("                    ");

            
            #line 122 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
               Write(Html.ValidationMessage("txtCity"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ol>\r\n            <ol>\r\n                <li" +
">\r\n                    <label");

WriteLiteral(" for=\"txtState\"");

WriteLiteral(">\r\n                        State/Province:\r\n                    </label>\r\n       " +
"         </li>\r\n                <li>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtState\"");

WriteLiteral(" name=\"txtState\"");

WriteLiteral(" \'");

            
            #line 132 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
                                                                 Write(Validation.For("txtState"));

            
            #line default
            #line hidden
WriteLiteral("\' value=\"");

            
            #line 132 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
                                                                                                     Write(SuppliersRecord.region);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                    &nbsp;&nbsp; \r\n");

WriteLiteral("                          ");

            
            #line 134 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
                     Write(Html.ValidationMessage("txtState"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ol>\r\n            <ol>\r\n                <li" +
">\r\n                    <label");

WriteLiteral(" for=\"txtZip\"");

WriteLiteral(">\r\n                        Zip/Postal Code:\r\n                    </label>\r\n      " +
"          </li>\r\n                <li>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtZip\"");

WriteLiteral(" name=\"txtZip\"");

WriteAttribute("value", Tuple.Create("  value=\"", 4795), Tuple.Create("\"", 4831)
            
            #line 144 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
, Tuple.Create(Tuple.Create("", 4804), Tuple.Create<System.Object, System.Int32>(SuppliersRecord.postalcode
            
            #line default
            #line hidden
, 4804), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                    ");

            
            #line 145 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
               Write(Html.ValidationMessage("txtZip"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ol>\r\n            <ol>\r\n                <li" +
">\r\n                    <label");

WriteLiteral(" for=\"txtCountry\"");

WriteLiteral(">\r\n                        Country:\r\n                    </label>\r\n              " +
"  </li>\r\n                <li>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtCountry\"");

WriteLiteral(" name=\"txtCountry\"");

WriteAttribute("value", Tuple.Create("  value=\"", 5201), Tuple.Create("\"", 5234)
            
            #line 155 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
 , Tuple.Create(Tuple.Create("", 5210), Tuple.Create<System.Object, System.Int32>(SuppliersRecord.country
            
            #line default
            #line hidden
, 5210), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                    ");

            
            #line 156 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
               Write(Html.ValidationMessage("txtCountry"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ol>\r\n            <ol>\r\n                <li" +
">\r\n                    <label");

WriteLiteral(" for=\"txtEmail\"");

WriteLiteral(">\r\n                        Email:\r\n                    </label>\r\n                " +
"</li>\r\n                <li>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtEmail\"");

WriteLiteral(" name=\"txtEmail\"");

WriteLiteral("  value=");

WriteLiteral(" \"");

            
            #line 166 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
                                                                         Write(SuppliersRecord.Email);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\r\n                </li>\r\n            </ol>\r\n            <ol>\r\n             " +
"   <li>\r\n                    <label");

WriteLiteral(" for=\"txtPhone\"");

WriteLiteral(">\r\n                        Phone:\r\n                    </label>\r\n                " +
"</li>\r\n                <li>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtPhone\"");

WriteLiteral(" name=\"txtPhone\"");

WriteAttribute("value", Tuple.Create("    value=\"", 5941), Tuple.Create("\"", 5974)
            
            #line 177 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
, Tuple.Create(Tuple.Create("", 5952), Tuple.Create<System.Object, System.Int32>(SuppliersRecord.phone
            
            #line default
            #line hidden
, 5952), false)
);

WriteLiteral("  />\r\n\r\n                </li>\r\n            </ol>\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"UpdateConfirm\"");

WriteLiteral(" name=\"UpdateConfirm\"");

WriteLiteral(" value=\"Confirm\"");

WriteLiteral(" />\r\n\r\n        </div>\r\n    </fieldset>\r\n    <p>\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"deleteConfirm\"");

WriteLiteral("  name=\"deleteConfirm\"");

WriteLiteral(" value=\"Delete Supplier\"");

WriteLiteral("  ");

            
            #line 186 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
                                                                                                if (SuppliersRecord.supplierid != 0)
                                                                                               {
            
            #line default
            #line hidden
WriteLiteral("style=\"display:none;\"");

            
            #line 187 "I:\Company\MensClothe\Admin\Supplier\RemoveSupplier.cshtml"
                                                                                                                                  }
            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    </p>\r\n    <ul>\r\n        <li><a href=\"~/\">Home</a></li>\r\n        <li><a " +
"href=\"~/Admin/Admin\">Admin</a></li>\r\n\r\n    </ul>\r\n</form>\r\n");

        }
    }
}
